use <your-database-name>;

create table Category(
	id int primary key identity(1,1),
	nameCategory varchar(50)
);

create table Difficulty(
	id int primary key identity(1,1),
	nameDifficulty varchar(50)
);

create table Questions(
	id int primary key identity(1,1),
	questionText varchar(max),
	correctAnswer varchar(max),
	option1 varchar(max),
	option2 varchar(max),
	option3 varchar(max),
	diff_id int foreign key(diff_id) references Difficulty(id),
	cat_id int foreign key(cat_id) references Category(id)
);

create table WrittenQuestions(
	id int primary key identity(1,1),
	questionText varchar(max),
	correctAnswer varchar(max),
	diff_id int foreign key(diff_id) references Difficulty(id),
	cat_id int foreign key(cat_id) references Category(id)
);

create table MultipleChoiceQuestion(
	id int primary key identity(1,1),
	questionText varchar(max),
	correctAnswer varchar(max),
	option1 varchar(max),
	option2 varchar(max),
	option3 varchar(max),
	option4 varchar(max),
	diff_id int foreign key(diff_id) references Difficulty(id),
	cat_id int foreign key(cat_id) references Category(id)
);

create table TrueFalseQuestions (
    id int primary key identity,
    questionText varchar(MAX),
    correctAnswer bit,
    diff_id int foreign key(diff_id) references Difficulty(id),
	cat_id int foreign key(cat_id) references Category(id)
);


create table Player(
	id int primary key identity(1,1),
	username varchar(50),
	userPassword varchar(50),
	score int
);

insert into Difficulty(nameDifficulty) values ('Easy'),('Medium'),('Hard');

insert into Category(nameCategory) values ('Geography'), ('History'), ('Biology'), ('Films');

insert into Questions (questionText, correctAnswer, option1, option2, option3, diff_id, cat_id)
values
('What is the powerhouse of the cell?', 'Mitochondria', 'Nucleus', 'Mitochondria', 'Ribosome', 1, 3),
('Which organ is responsible for pumping blood through the body?', 'Heart', 'Heart', 'Lungs', 'Liver', 1, 3),
('What is the process by which plants make their food?', 'Photosynthesis', 'Respiration', 'Photosynthesis', 'Osmosis', 1, 3),
('What is the largest organ in the human body?', 'Skin', 'Heart', 'Lungs', 'Skin', 1, 3),
('How many bones are in the adult human body?', '206', '206', '201', '210', 1, 3),
('What is the basic unit of life?', 'Cell', 'Tissue', 'Cell', 'Organ', 1, 3),
('What is the primary gas exchanged in photosynthesis?', 'Carbon dioxide', 'Carbon dioxide', 'Oxygen', 'Nitrogen', 1, 3),
('Which part of the plant is responsible for reproduction?', 'Flower', 'Leaf', 'Flower', 'Root', 1, 3),
('Which blood cells help fight infections?', 'White blood cells', 'Red blood cells', 'Platelets', 'White blood cells', 1, 3),
('What is the function of red blood cells?', 'Transport oxygen', 'Clot blood', 'Transport oxygen', 'Fight infection', 1, 3),
('What organ filters waste from the blood?', 'Kidney', 'Liver', 'Kidney', 'Lungs', 1, 3),
('What is the main pigment in plants?', 'Chlorophyll', 'Melanin', 'Hemoglobin', 'Chlorophyll', 1, 3),
('What is the name of a group of tissues working together?', 'Organ', 'Cell', 'Organ', 'System', 1, 3),
('What is the role of the stomach?', 'Digestion', 'Circulation', 'Digestion', 'Respiration', 1, 3),
('What is the name of the process in which water moves through a semi-permeable membrane?', 'Osmosis', 'Diffusion', 'Osmosis', 'Filtration', 1, 3),
('What is the main function of the lungs?', 'Gas exchange', 'Digestion', 'Gas exchange', 'Filtration', 1, 3),
('What is the smallest unit of an element?', 'Atom', 'Cell', 'Atom', 'Molecule', 1, 3),
('What is the term for animals that only eat plants?', 'Herbivores', 'Omnivores', 'Herbivores', 'Carnivores', 1, 3),
('What is the outer layer of the skin called?', 'Epidermis', 'Dermis', 'Epidermis', 'Hypodermis', 1, 3),
('What is the process by which the body breaks down food?', 'Digestion', 'Respiration', 'Digestion', 'Excretion', 1, 3),
('Which organelle is responsible for photosynthesis?', 'Chloroplast', 'Mitochondria', 'Chloroplast', 'Nucleus', 1, 3),
('What do we call the study of living things?', 'Biology', 'Chemistry', 'Biology', 'Physics', 1, 3),
('What is the liquid part of blood called?', 'Plasma', 'Platelets', 'Plasma', 'Serum', 1, 3),
('What is the hardest substance in the human body?', 'Tooth enamel', 'Bone', 'Tooth enamel', 'Cartilage', 1, 3),
('What organ is responsible for detoxifying the blood?', 'Liver', 'Kidney', 'Liver', 'Pancreas', 1, 3);

insert into Questions (questionText, correctAnswer, option1, option2, option3, diff_id, cat_id)
values
('What is the primary function of the kidneys?', 'Filter blood', 'Filter blood', 'Produce hormones', 'Digest food', 2, 3),
('Which vitamin is produced by the skin when exposed to sunlight?', 'Vitamin D', 'Vitamin D', 'Vitamin C', 'Vitamin A', 2, 3),
('What is the primary component of the cell membrane?', 'Phospholipids', 'Proteins', 'Carbohydrates', 'Phospholipids', 2, 3),
('What type of blood vessel carries blood away from the heart?', 'Arteries', 'Veins', 'Arteries', 'Capillaries', 2, 3),
('What is the smallest bone in the human body?', 'Stapes', 'Stapes', 'Humerus', 'Femur', 2, 3),
('Which part of the brain controls balance?', 'Cerebellum', 'Cerebellum', 'Medulla', 'Cerebrum', 2, 3),
('What is the largest mammal in the world?', 'Blue whale', 'Elephant', 'Blue whale', 'Giraffe', 2, 3),
('Which organelle is responsible for energy production?', 'Mitochondria', 'Mitochondria', 'Ribosome', 'Nucleus', 2, 3),
('What is the term for animals that eat both plants and meat?', 'Omnivores', 'Carnivores', 'Herbivores', 'Omnivores', 2, 3),
('Which blood type is known as the universal donor?', 'O negative', 'A positive', 'B positive', 'O negative', 2, 3),
('What type of cells are responsible for transmitting nerve impulses?', 'Neurons', 'Neurons', 'Glial cells', 'Muscle cells', 2, 3),
('What is the main hormone responsible for regulating blood sugar?', 'Insulin', 'Adrenaline', 'Insulin', 'Cortisol', 2, 3),
('Which organ produces bile?', 'Liver', 'Pancreas', 'Liver', 'Gallbladder', 2, 3),
('What is the name of the protein that carries oxygen in the blood?', 'Hemoglobin', 'Myoglobin', 'Hemoglobin', 'Keratin', 2, 3),
('What type of macromolecule are enzymes?', 'Proteins', 'Carbohydrates', 'Proteins', 'Lipids', 2, 3),
('Which part of the eye controls the amount of light entering?', 'Iris', 'Retina', 'Iris', 'Cornea', 2, 3),
('What is the term for programmed cell death?', 'Apoptosis', 'Necrosis', 'Apoptosis', 'Mitosis', 2, 3),
('Which gas do humans exhale?', 'Carbon dioxide', 'Oxygen', 'Nitrogen', 'Carbon dioxide', 2, 3),
('What is the main structural material in plant cell walls?', 'Cellulose', 'Chitin', 'Cellulose', 'Lignin', 2, 3),
('What is the name of the process where cells divide to produce gametes?', 'Meiosis', 'Mitosis', 'Meiosis', 'Binary fission', 2, 3),
('Which system in the body controls hormones?', 'Endocrine system', 'Nervous system', 'Endocrine system', 'Respiratory system', 2, 3),
('What is the function of ribosomes?', 'Protein synthesis', 'Energy production', 'Protein synthesis', 'Waste removal', 2, 3),
('Which vitamin is essential for blood clotting?', 'Vitamin K', 'Vitamin C', 'Vitamin K', 'Vitamin A', 2, 3),
('Which cells are responsible for producing antibodies?', 'B cells', 'T cells', 'B cells', 'Macrophages', 2, 3),
('What is the name of the disease caused by a deficiency of Vitamin C?', 'Scurvy', 'Rickets', 'Scurvy', 'Anemia', 2, 3);

insert into Questions (questionText, correctAnswer, option1, option2, option3, diff_id, cat_id)
values
('What is the name of the process by which DNA is copied?', 'Replication', 'Transcription', 'Replication', 'Translation', 3, 3),
('What is the main function of the liver?', 'Detoxification', 'Digestion', 'Detoxification', 'Hormone production', 3, 3),
('What is the term for the study of fungi?', 'Mycology', 'Bacteriology', 'Mycology', 'Virology', 3, 3),
('What is the powerhouse of the cell?', 'Mitochondria', 'Nucleus', 'Mitochondria', 'Ribosome', 3, 3),
('Which molecule carries genetic information?', 'DNA', 'RNA', 'DNA', 'Protein', 3, 3),
('What type of RNA carries amino acids to the ribosome?', 'tRNA', 'mRNA', 'tRNA', 'rRNA', 3, 3),
('What is the process of converting mRNA into a protein called?', 'Translation', 'Replication', 'Transcription', 'Translation', 3, 3),
('Which organelle is involved in protein modification and packaging?', 'Golgi apparatus', 'Endoplasmic reticulum', 'Golgi apparatus', 'Lysosome', 3, 3),
('What is the term for the movement of water across a semipermeable membrane?', 'Osmosis', 'Diffusion', 'Osmosis', 'Active transport', 3, 3),
('What is the main pigment responsible for photosynthesis?', 'Chlorophyll', 'Carotene', 'Chlorophyll', 'Xanthophyll', 3, 3),
('Which part of the brain regulates homeostasis and hormone release?', 'Hypothalamus', 'Cerebellum', 'Hypothalamus', 'Medulla', 3, 3),
('What is the name of the enzyme that unwinds DNA during replication?', 'Helicase', 'Polymerase', 'Helicase', 'Ligase', 3, 3),
('What are the basic building blocks of proteins?', 'Amino acids', 'Nucleotides', 'Amino acids', 'Monosaccharides', 3, 3),
('Which blood cells are responsible for clotting?', 'Platelets', 'Red blood cells', 'Platelets', 'White blood cells', 3, 3),
('What type of bond holds the two strands of DNA together?', 'Hydrogen bond', 'Covalent bond', 'Hydrogen bond', 'Ionic bond', 3, 3),
('What is the term for a change in the DNA sequence?', 'Mutation', 'Transcription', 'Mutation', 'Replication', 3, 3),
('Which organelle contains enzymes for breaking down waste?', 'Lysosome', 'Peroxisome', 'Lysosome', 'Mitochondria', 3, 3),
('What is the name of the cycle plants use to fix carbon dioxide?', 'Calvin cycle', 'Krebs cycle', 'Calvin cycle', 'Glycolysis', 3, 3),
('What is the name of the pigment responsible for red color in blood?', 'Hemoglobin', 'Myoglobin', 'Hemoglobin', 'Chlorophyll', 3, 3),
('Which type of RNA is involved in splicing?', 'snRNA', 'mRNA', 'snRNA', 'tRNA', 3, 3),
('What is the primary role of mitochondria?', 'ATP production', 'Protein synthesis', 'ATP production', 'Cell division', 3, 3),
('Which disease is caused by the deficiency of insulin?', 'Diabetes mellitus', 'Hypothyroidism', 'Diabetes mellitus', 'Anemia', 3, 3),
('What is the main function of ribosomes?', 'Protein synthesis', 'Lipid synthesis', 'Protein synthesis', 'Energy production', 3, 3),
('Which cells in the immune system produce antibodies?', 'B cells', 'T cells', 'B cells', 'Macrophages', 3, 3),
('What is the name of the DNA sequence that signals the start of transcription?', 'Promoter', 'Enhancer', 'Promoter', 'Operator', 3, 3);

insert into Questions (questionText, correctAnswer, option1, option2, option3, diff_id, cat_id)
values
('Who directed the movie "Jurassic Park"?', 'Steven Spielberg', 'Steven Spielberg', 'James Cameron', 'Martin Scorsese', 1, 4),
('Which movie features the character "Harry Potter"?', 'Harry Potter and the Sorcerer’s Stone', 'Harry Potter and the Sorcerer’s Stone', 'The Lord of the Rings', 'The Hunger Games', 1, 4),
('What is the name of the spaceship in "Star Wars"?', 'Millennium Falcon', 'Millennium Falcon', 'Enterprise', 'Serenity', 1, 4),
('Who played Jack in "Titanic"?', 'Leonardo DiCaprio', 'Leonardo DiCaprio', 'Brad Pitt', 'Tom Cruise', 1, 4),
('In which movie does the character "Forrest Gump" appear?', 'Forrest Gump', 'Cast Away', 'Forrest Gump', 'Saving Private Ryan', 1, 4),
('Which animated movie features a talking snowman named Olaf?', 'Frozen', 'Frozen', 'Tangled', 'Moana', 1, 4),
('What is the name of the wizarding school in Harry Potter?', 'Hogwarts', 'Hogwarts', 'Beauxbatons', 'Durmstrang', 1, 4),
('Who is the superhero alter ego of Bruce Wayne?', 'Batman', 'Spider-Man', 'Batman', 'Superman', 1, 4),
('Which movie is about toys coming to life?', 'Toy Story', 'Toy Story', 'The Incredibles', 'Monsters, Inc.', 1, 4),
('Who directed "E.T. the Extra-Terrestrial"?', 'Steven Spielberg', 'James Cameron', 'Steven Spielberg', 'George Lucas', 1, 4),
('Which movie features the song "Let It Go"?', 'Frozen', 'Frozen', 'Moana', 'Tangled', 1, 4),
('Who played Iron Man in the Marvel Cinematic Universe?', 'Robert Downey Jr.', 'Chris Evans', 'Robert Downey Jr.', 'Chris Hemsworth', 1, 4),
('What is the name of the kingdom in "The Lion King"?', 'Pride Lands', 'Pride Lands', 'Narnia', 'Agrabah', 1, 4),
('In which movie do dinosaurs escape from a theme park?', 'Jurassic Park', 'Jurassic Park', 'King Kong', 'Godzilla', 1, 4),
('Who is the main character in the "Pirates of the Caribbean" series?', 'Jack Sparrow', 'Jack Sparrow', 'Will Turner', 'Hector Barbossa', 1, 4),
('Which movie features a character named "Elsa"?', 'Frozen', 'Tangled', 'Frozen', 'Brave', 1, 4),
('What is the profession of the main character in "The Devil Wears Prada"?', 'Fashion Editor', 'Fashion Editor', 'Journalist', 'Teacher', 1, 4),
('Who starred as the lead in "Mission: Impossible"?', 'Tom Cruise', 'Tom Cruise', 'Matt Damon', 'Brad Pitt', 1, 4),
('Which movie is set in the city of New York and features Spider-Man?', 'Spider-Man', 'Spider-Man', 'Batman', 'Iron Man', 1, 4),
('What type of creature is Shrek?', 'Ogre', 'Elf', 'Ogre', 'Troll', 1, 4),
('Who directed the "Lord of the Rings" trilogy?', 'Peter Jackson', 'Steven Spielberg', 'James Cameron', 'Peter Jackson', 1, 4),
('What is the name of the hobbit played by Elijah Wood?', 'Frodo Baggins', 'Bilbo Baggins', 'Samwise Gamgee', 'Frodo Baggins', 1, 4),
('Which movie features the quote "May the Force be with you"?', 'Star Wars', 'Star Trek', 'Star Wars', 'Guardians of the Galaxy', 1, 4),
('What is the color of the superhero costume of Superman?', 'Blue and red', 'Blue and red', 'Green and black', 'Yellow and black', 1, 4),
('Which animated movie features a fish named Nemo?', 'Finding Nemo', 'Finding Nemo', 'Shark Tale', 'The Little Mermaid', 1, 4);

insert into Questions (questionText, correctAnswer, option1, option2, option3, diff_id, cat_id)
values
('In "Inception," what is the term used for entering someone’s dreams?', 'Dream sharing', 'Dream sharing', 'Mind reading', 'Time travel', 2, 4),
('Who played the character "Joker" in "The Dark Knight"?', 'Heath Ledger', 'Joaquin Phoenix', 'Heath Ledger', 'Jared Leto', 2, 4),
('What is the name of the kingdom in "Game of Thrones"?', 'Westeros', 'Westeros', 'Narnia', 'Middle-earth', 2, 4),
('Which movie features the song "My Heart Will Go On"?', 'Titanic', 'Titanic', 'Avatar', 'The Bodyguard', 2, 4),
('In "The Matrix," what color pill does Neo take?', 'Red', 'Blue', 'Red', 'Green', 2, 4),
('Who directed "Pulp Fiction"?', 'Quentin Tarantino', 'Martin Scorsese', 'Quentin Tarantino', 'Steven Spielberg', 2, 4),
('What is the name of the hobbit who destroys the One Ring?', 'Frodo Baggins', 'Bilbo Baggins', 'Frodo Baggins', 'Samwise Gamgee', 2, 4),
('Which actor portrayed the character "Forrest Gump"?', 'Tom Hanks', 'Tom Cruise', 'Tom Hanks', 'Brad Pitt', 2, 4),
('What is the main setting for the movie "The Shawshank Redemption"?', 'Prison', 'Hospital', 'Prison', 'School', 2, 4),
('In "Guardians of the Galaxy," what is the real name of Star-Lord?', 'Peter Quill', 'Peter Quill', 'Tony Stark', 'Bruce Wayne', 2, 4),
('Who composed the score for "Star Wars"?', 'John Williams', 'Hans Zimmer', 'John Williams', 'James Horner', 2, 4),
('Which actress plays "Black Widow" in the Marvel movies?', 'Scarlett Johansson', 'Scarlett Johansson', 'Emily Blunt', 'Natalie Portman', 2, 4),
('What is the name of the AI in "2001: A Space Odyssey"?', 'HAL 9000', 'TARS', 'HAL 9000', 'Skynet', 2, 4),
('In which movie does Tom Hanks play a character stranded on an island?', 'Cast Away', 'Cast Away', 'Saving Private Ryan', 'Forrest Gump', 2, 4),
('Which film features the character "Tyler Durden"?', 'Fight Club', 'Se7en', 'Fight Club', 'The Matrix', 2, 4),
('What is the name of the city where "The Dark Knight" is set?', 'Gotham', 'Metropolis', 'Gotham', 'Central City', 2, 4),
('Which film won the Oscar for Best Picture in 1994?', 'Forrest Gump', 'Pulp Fiction', 'Forrest Gump', 'The Shawshank Redemption', 2, 4),
('What is the name of the protagonist in the "Die Hard" series?', 'John McClane', 'Jack Bauer', 'John McClane', 'Jason Bourne', 2, 4),
('Who directed "The Grand Budapest Hotel"?', 'Wes Anderson', 'Wes Anderson', 'Quentin Tarantino', 'Paul Thomas Anderson', 2, 4),
('Which movie features the line "Ill be back"?', 'The Terminator', 'Predator', 'The Terminator', 'RoboCop', 2, 4),
('What is the name of the main antagonist in "The Silence of the Lambs"?', 'Hannibal Lecter', 'Norman Bates', 'Hannibal Lecter', 'Freddy Krueger', 2, 4),
('Which actress stars in "La La Land"?', 'Emma Stone', 'Emma Watson', 'Emma Stone', 'Jennifer Lawrence', 2, 4),
('What year was "Avatar" released?', '2009', '2009', '2010', '2012', 2, 4),
('Which movie is about a robot named WALL-E?', 'WALL-E', 'Robots', 'WALL-E', 'Big Hero 6', 2, 4),
('What is the fictional language spoken by the Na’vi in "Avatar"?', 'Na’vi', 'Elvish', 'Na’vi', 'Klingon', 2, 4);

insert into Questions (questionText, correctAnswer, option1, option2, option3, diff_id, cat_id)
values
('Which film won the first Academy Award for Best Picture?', 'Wings (1927)', 'Wings (1927)', 'The Jazz Singer', 'Sunrise', 3, 4),
('In "The Godfather," what is the name of Michael Corleone’s wife?', 'Kay Adams', 'Kay Adams', 'Connie Corleone', 'Carla', 3, 4),
('Who played the role of the lead antagonist in "No Country for Old Men"?', 'Javier Bardem', 'Josh Brolin', 'Javier Bardem', 'Tommy Lee Jones', 3, 4),
('Which director is known for the use of the “dolly zoom” effect?', 'Alfred Hitchcock', 'Stanley Kubrick', 'Alfred Hitchcock', 'Steven Spielberg', 3, 4),
('What year was the original "Blade Runner" film released?', '1982', '1982', '1992', '1979', 3, 4),
('In "Schindler’s List," what is Oskar Schindler’s profession?', 'Industrialist', 'Industrialist', 'Soldier', 'Lawyer', 3, 4),
('Which film features a character named Anton Chigurh?', 'No Country for Old Men', 'No Country for Old Men', 'The Hurt Locker', 'There Will Be Blood', 3, 4),
('What is the name of the spacecraft in "2001: A Space Odyssey"?', 'Discovery One', 'Endeavour', 'Discovery One', 'Enterprise', 3, 4),
('Who composed the music for "The Lord of the Rings" trilogy?', 'Howard Shore', 'John Williams', 'Howard Shore', 'Hans Zimmer', 3, 4),
('In "The Prestige," what is the profession of the two main characters?', 'Magicians', 'Detectives', 'Magicians', 'Scientists', 3, 4),
('What is the original language of the film "Pan’s Labyrinth"?', 'Spanish', 'Spanish', 'French', 'Italian', 3, 4),
('Which 1927 silent film is considered a masterpiece of German Expressionism?', 'Metropolis', 'Nosferatu', 'Metropolis', 'The Cabinet of Dr. Caligari', 3, 4),
('What is the full name of the character "Indiana Jones"?', 'Dr. Henry Walton Jones Jr.', 'Dr. Henry Walton Jones Jr.', 'Dr. John Watson', 'Dr. Marcus Brody', 3, 4),
('Who directed "Apocalypse Now"?', 'Francis Ford Coppola', 'Martin Scorsese', 'Francis Ford Coppola', 'Francis Ford Coppola', 3, 4),
('Which film’s famous line is “Rosebud”?', 'Citizen Kane', 'Casablanca', 'Citizen Kane', 'The Maltese Falcon', 3, 4),
('In "Se7en," what is the first sin the killer punishes?', 'Gluttony', 'Greed', 'Gluttony', 'Lust', 3, 4),
('Who starred as the lead in the original "King Kong" (1933)?', 'Fay Wray', 'Merian C. Cooper', 'Fay Wray', 'Naomi Watts', 3, 4),
('What is the name of the fictional hotel in "The Shining"?', 'The Overlook Hotel', 'The Bates Motel', 'The Overlook Hotel', 'The Continental', 3, 4),
('Which film was directed by Andrei Tarkovsky?', 'Solaris', 'Solaris', 'Stalker', 'Both', 3, 4),
('What is the signature weapon of the character Jason Voorhees?', 'Machete', 'Chainsaw', 'Machete', 'Knife', 3, 4),
('Who played the role of Clarice Starling in "The Silence of the Lambs"?', 'Jodie Foster', 'Julianne Moore', 'Jodie Foster', 'Gillian Anderson', 3, 4),
('Which movie features a character called "Tyler Durden"?', 'Fight Club', 'Fight Club', 'American Psycho', 'The Social Network', 3, 4),
('In "Psycho," what is Norman Bates’ mother’s first name?', 'Norma', 'Norma', 'Marion', 'Lila', 3, 4),
('Which film is set during the Vietnam War and directed by Stanley Kubrick?', 'Full Metal Jacket', 'Platoon', 'Full Metal Jacket', 'Apocalypse Now', 3, 4),
('Who directed "The Grand Budapest Hotel"?', 'Wes Anderson', 'Wes Anderson', 'Tim Burton', 'David Fincher', 3, 4),
('Which film features the quote, “Here’s looking at you, kid”?', 'Casablanca', 'Gone with the Wind', 'Casablanca', 'It’s a Wonderful Life', 3, 4);

insert into Questions (questionText, correctAnswer, option1, option2, option3, diff_id, cat_id)
values
('What is the capital of France?', 'Paris', 'Paris', 'Berlin', 'Madrid', 1, 1),
('What is the largest ocean in the world?', 'Pacific Ocean', 'Atlantic Ocean', 'Indian Ocean', 'Pacific Ocean', 1, 1),
('What is the capital of Italy?', 'Rome', 'Rome', 'Venice', 'Milan', 1, 1),
('Which continent is also a country?', 'Australia', 'Australia', 'Asia', 'Antarctica', 1, 1),
('What is the capital of Canada?', 'Ottawa', 'Ottawa', 'Toronto', 'Vancouver', 1, 1),
('What is the capital of Australia?', 'Canberra', 'Canberra', 'Sydney', 'Melbourne', 1, 1),
('What is the smallest country in the world?', 'Vatican City', 'Vatican City', 'Monaco', 'San Marino', 1, 1),
('Which desert is located in Africa?', 'Sahara Desert', 'Sahara Desert', 'Kalahari Desert', 'Gobi Desert', 1, 1),
('What is the name of the tallest mountain in the world?', 'Mount Everest', 'K2', 'Kilimanjaro', 'Mount Everest', 1, 1),
('Which river flows through Egypt?', 'Nile', 'Amazon', 'Nile', 'Yangtze', 1, 1),
('What continent is Egypt part of?', 'Africa', 'Asia', 'Africa', 'Europe', 1, 1),
('Which city is known as the "Big Apple"?', 'New York City', 'New York City', 'Los Angeles', 'Chicago', 1, 1),
('Which country is famous for the Eiffel Tower?', 'France', 'Italy', 'Germany', 'France', 1, 1),
('What ocean is on the west coast of the United States?', 'Pacific Ocean', 'Atlantic Ocean', 'Indian Ocean', 'Pacific Ocean', 1, 1),
('What is the capital city of Japan?', 'Tokyo', 'Kyoto', 'Tokyo', 'Osaka', 1, 1),
('Which continent has the most countries?', 'Africa', 'Asia', 'Africa', 'Europe', 1, 1),
('What is the longest river in the world?', 'Nile', 'Amazon', 'Nile', 'Yangtze', 1, 1),
('Which country is known as the Land of the Rising Sun?', 'Japan', 'China', 'Japan', 'South Korea', 1, 1),
('Which continent is the Sahara Desert located on?', 'Africa', 'Asia', 'Africa', 'South America', 1, 1),
('Which U.S. state is famous for Hollywood?', 'California', 'Florida', 'California', 'Nevada', 1, 1),
('What is the capital of Germany?', 'Berlin', 'Munich', 'Berlin', 'Frankfurt', 1, 1),
('Which country has the Great Barrier Reef?', 'Australia', 'Australia', 'New Zealand', 'South Africa', 1, 1),
('Which ocean surrounds the Maldives?', 'Indian Ocean', 'Pacific Ocean', 'Atlantic Ocean', 'Indian Ocean', 1, 1),
('Which continent is home to the Amazon rainforest?', 'South America', 'Africa', 'South America', 'Asia', 1, 1),
('What is the capital city of Brazil?', 'Brasília', 'Rio de Janeiro', 'S?o Paulo', 'Brasília', 1, 1);

insert into Questions (questionText, correctAnswer, option1, option2, option3, diff_id, cat_id)
values
('Which country has the most islands in the world?', 'Sweden', 'Canada', 'Sweden', 'Indonesia', 2, 1),
('Which continent is the Amazon Rainforest located on?', 'South America', 'South America', 'Africa', 'Asia', 2, 1),
('What is the longest river in Asia?', 'Yangtze', 'Yangtze', 'Mekong', 'Ganges', 2, 1),
('What is the name of the smallest country in Europe?', 'Vatican City', 'Monaco', 'Vatican City', 'San Marino', 2, 1),
('Which river flows through Paris?', 'Seine', 'Thames', 'Seine', 'Danube', 2, 1),
('Which U.S. state has the most coastline?', 'Alaska', 'California', 'Florida', 'Alaska', 2, 1),
('What is the name of the largest coral reef system in the world?', 'Great Barrier Reef', 'Great Barrier Reef', 'Red Sea Reef', 'Belize Barrier Reef', 2, 1),
('What is the second-largest country by land area?', 'Canada', 'Russia', 'Canada', 'United States', 2, 1),
('Which country has the highest number of volcanoes?', 'Indonesia', 'Japan', 'Indonesia', 'Italy', 2, 1),
('What is the largest lake in the world?', 'Caspian Sea', 'Lake Superior', 'Lake Victoria', 'Caspian Sea', 2, 1),
('Which mountain range is the longest in the world?', 'Andes', 'Rockies', 'Himalayas', 'Andes', 2, 1),
('What is the capital of New Zealand?', 'Wellington', 'Auckland', 'Wellington', 'Christchurch', 2, 1),
('Which country is famous for the fjords?', 'Norway', 'Iceland', 'Sweden', 'Norway', 2, 1),
('What is the primary language spoken in Brazil?', 'Portuguese', 'Spanish', 'Portuguese', 'French', 2, 1),
('Which desert covers much of Botswana and Namibia?', 'Kalahari', 'Sahara', 'Kalahari', 'Gobi', 2, 1),
('What is the capital of Kenya?', 'Nairobi', 'Nairobi', 'Kampala', 'Addis Ababa', 2, 1),
('Which country has the most pyramids?', 'Sudan', 'Egypt', 'Sudan', 'Mexico', 2, 1),
('Which city is known as the City of a Hundred Spires?', 'Prague', 'Vienna', 'Prague', 'Budapest', 2, 1),
('Which U.S. state is known as the “Sunshine State”?', 'Florida', 'California', 'Florida', 'Texas', 2, 1),
('Which ocean is the Bermuda Triangle located in?', 'Atlantic Ocean', 'Pacific Ocean', 'Indian Ocean', 'Atlantic Ocean', 2, 1),
('Which country is home to Machu Picchu?', 'Peru', 'Chile', 'Peru', 'Bolivia', 2, 1),
('Which city is the capital of Canada?', 'Ottawa', 'Toronto', 'Ottawa', 'Montreal', 2, 1),
('Which continent is Madagascar part of?', 'Africa', 'Asia', 'Africa', 'South America', 2, 1),
('What is the largest island in the Mediterranean Sea?', 'Sicily', 'Corsica', 'Sicily', 'Crete', 2, 1),
('Which country shares the longest border with the United States?', 'Canada', 'Mexico', 'Canada', 'Russia', 2, 1);

insert into Questions (questionText, correctAnswer, option1, option2, option3, diff_id, cat_id)
values
('What is the capital of Bhutan?', 'Thimphu', 'Thimphu', 'Kathmandu', 'Paro', 3, 1),
('Which country has the most official languages?', 'Bolivia', 'India', 'South Africa', 'Bolivia', 3, 1),
('What is the name of the deepest lake in the world?', 'Lake Baikal', 'Lake Tanganyika', 'Lake Baikal', 'Lake Superior', 3, 1),
('Which desert is the coldest desert in the world?', 'Antarctic Desert', 'Gobi Desert', 'Antarctic Desert', 'Arctic Desert', 3, 1),
('What is the capital city of Kyrgyzstan?', 'Bishkek', 'Almaty', 'Tashkent', 'Bishkek', 3, 1),
('Which mountain is the tallest volcano in the world?', 'Ojos del Salado', 'Mount Fuji', 'Ojos del Salado', 'Mauna Loa', 3, 1),
('Which country is home to the Danakil Depression, one of the hottest places on Earth?', 'Ethiopia', 'Eritrea', 'Ethiopia', 'Djibouti', 3, 1),
('What is the longest river in Europe?', 'Volga', 'Danube', 'Volga', 'Rhine', 3, 1),
('Which island nation is the smallest by area in the Caribbean?', 'Saint Kitts and Nevis', 'Dominica', 'Saint Kitts and Nevis', 'Grenada', 3, 1),
('What is the capital of Turkmenistan?', 'Ashgabat', 'Ashgabat', 'Tashkent', 'Dushanbe', 3, 1),
('Which country’s territory includes the region of Transylvania?', 'Romania', 'Romania', 'Hungary', 'Bulgaria', 3, 1),
('What is the capital of Liechtenstein?', 'Vaduz', 'Vaduz', 'Bern', 'Zurich', 3, 1),
('Which country has the largest proven oil reserves?', 'Venezuela', 'Saudi Arabia', 'Russia', 'Venezuela', 3, 1),
('What is the capital city of the Maldives?', 'Malé', 'Malé', 'Colombo', 'Male', 3, 1),
('Which country is the only one to lie entirely above 1,000 meters in elevation?', 'Lesotho', 'Bhutan', 'Nepal', 'Lesotho', 3, 1),
('What is the largest peninsula in the world?', 'Arabian Peninsula', 'Indian Peninsula', 'Arabian Peninsula', 'Scandinavian Peninsula', 3, 1),
('Which river forms part of the border between the United States and Mexico?', 'Rio Grande', 'Colorado River', 'Rio Grande', 'Mississippi River', 3, 1),
('What is the capital city of Madagascar?', 'Antananarivo', 'Antananarivo', 'Nairobi', 'Maputo', 3, 1),
('Which mountain range separates Europe and Asia?', 'Ural Mountains', 'Caucasus Mountains', 'Ural Mountains', 'Alps', 3, 1),
('Which country has the highest waterfall in the world?', 'Venezuela', 'Norway', 'Canada', 'Venezuela', 3, 1),
('Which city is known as the “Venice of the North”?', 'Saint Petersburg', 'Amsterdam', 'Bruges', 'Saint Petersburg', 3, 1),
('What is the capital of Papua New Guinea?', 'Port Moresby', 'Suva', 'Port Moresby', 'Honiara', 3, 1),
('Which is the smallest independent country in Asia?', 'Maldives', 'Bhutan', 'Maldives', 'Singapore', 3, 1),
('What is the name of the strait that separates Spain and Morocco?', 'Strait of Gibraltar', 'Strait of Hormuz', 'Strait of Gibraltar', 'Bosporus Strait', 3, 1),
('Which country has the largest number of lakes?', 'Canada', 'Finland', 'Canada', 'Russia', 3, 1),
('What is the capital of Kazakhstan?', 'Nur-Sultan', 'Almaty', 'Nur-Sultan', 'Tashkent', 3, 1);

insert into Questions (questionText, correctAnswer, option1, option2, option3, diff_id, cat_id)
values
('Who was the first President of the United States?', 'George Washington', 'George Washington', 'Thomas Jefferson', 'Abraham Lincoln', 1, 2),
('In what year did World War II start?', '1939', '1939', '1945', '1914', 1, 2),
('What was the name of the ship that carried the Pilgrims to America?', 'Mayflower', 'Mayflower', 'Santa Maria', 'Endeavour', 1, 2),
('Who was known as the Iron Lady?', 'Margaret Thatcher', 'Margaret Thatcher', 'Angela Merkel', 'Golda Meir', 1, 2),
('What year did the Titanic sink?', '1912', '1905', '1912', '1918', 1, 2),
('Who discovered America in 1492?', 'Christopher Columbus', 'Christopher Columbus', 'Leif Erikson', 'Ferdinand Magellan', 1, 2),
('What was the name of the last Queen of France?', 'Marie Antoinette', 'Catherine the Great', 'Marie Antoinette', 'Elizabeth I', 1, 2),
('Which war was fought between the North and South regions in the United States?', 'Civil War', 'Revolutionary War', 'Civil War', 'Vietnam War', 1, 2),
('Who was the first Emperor of Rome?', 'Augustus', 'Julius Caesar', 'Augustus', 'Nero', 1, 2),
('Which British king had six wives?', 'Henry VIII', 'Henry VII', 'Henry VIII', 'Edward VI', 1, 2),
('When was the Declaration of Independence signed?', '1776', '1776', '1787', '1791', 1, 2),
('Who invented the printing press?', 'Johannes Gutenberg', 'Johannes Gutenberg', 'Thomas Edison', 'Isaac Newton', 1, 2),
('What ancient civilization built the pyramids?', 'Egyptians', 'Romans', 'Greeks', 'Egyptians', 1, 2),
('Who was the famous nurse during the Crimean War?', 'Florence Nightingale', 'Florence Nightingale', 'Marie Curie', 'Clara Barton', 1, 2),
('What was the Renaissance?', 'A cultural rebirth in Europe', 'A war', 'A cultural rebirth in Europe', 'A disease', 1, 2),
('Who was the leader of the Nazi Party?', 'Adolf Hitler', 'Benito Mussolini', 'Joseph Stalin', 'Adolf Hitler', 1, 2),
('Which explorer is credited with circumnavigating the globe first?', 'Ferdinand Magellan', 'Christopher Columbus', 'Ferdinand Magellan', 'Vasco da Gama', 1, 2),
('What was the name of the first successful English colony in America?', 'Jamestown', 'Jamestown', 'Roanoke', 'Plymouth', 1, 2),
('Who was the Egyptian queen famous for her beauty and alliances with Roman leaders?', 'Cleopatra', 'Nefertiti', 'Cleopatra', 'Hatshepsut', 1, 2),
('Which war was fought between 1914 and 1918?', 'World War I', 'World War I', 'World War II', 'Korean War', 1, 2),
('What invention is Thomas Edison famous for?', 'The light bulb', 'The telephone', 'The light bulb', 'The airplane', 1, 2),
('Who wrote the Declaration of Independence?', 'Thomas Jefferson', 'Benjamin Franklin', 'Thomas Jefferson', 'John Adams', 1, 2),
('What was the name of the wall that separated East and West Berlin?', 'Berlin Wall', 'Berlin Wall', 'Great Wall of China', 'Hadrian’s Wall', 1, 2),
('Who was the famous civil rights leader known for his "I Have a Dream" speech?', 'Martin Luther King Jr.', 'Malcolm X', 'Martin Luther King Jr.', 'Rosa Parks', 1, 2),
('Which empire was ruled by Genghis Khan?', 'Mongol Empire', 'Ottoman Empire', 'Mongol Empire', 'Roman Empire', 1, 2);

insert into Questions (questionText, correctAnswer, option1, option2, option3, diff_id, cat_id)
values
('In what year did World War II end?', '1945', '1945', '1939', '1950', 2, 2),
('Which empire was ruled by Julius Caesar?', 'Roman Empire', 'Byzantine Empire', 'Roman Empire', 'Ottoman Empire', 2, 2),
('What was the name of the treaty that ended World War I?', 'Treaty of Versailles', 'Treaty of Paris', 'Treaty of Versailles', 'Treaty of Ghent', 2, 2),
('Who was the Prime Minister of the UK during most of World War II?', 'Winston Churchill', 'Neville Chamberlain', 'Winston Churchill', 'Clement Attlee', 2, 2),
('Who led the Russian Revolution in 1917?', 'Vladimir Lenin', 'Joseph Stalin', 'Vladimir Lenin', 'Leon Trotsky', 2, 2),
('What year did the Berlin Wall fall?', '1989', '1980', '1989', '1991', 2, 2),
('Who was the longest-reigning British monarch before Queen Elizabeth II?', 'Queen Victoria', 'Queen Victoria', 'George III', 'Edward VII', 2, 2),
('What was the name of the Spanish Armada’s leader?', 'Duke of Medina Sidonia', 'Francis Drake', 'Duke of Medina Sidonia', 'Philip II', 2, 2),
('Who was the first President of the Soviet Union?', 'Mikhail Gorbachev', 'Joseph Stalin', 'Mikhail Gorbachev', 'Nikita Khrushchev', 2, 2),
('What year did the American Civil War end?', '1865', '1863', '1865', '1870', 2, 2),
('Which French leader declared himself Emperor in 1804?', 'Napoleon Bonaparte', 'Louis XVI', 'Napoleon Bonaparte', 'Charles de Gaulle', 2, 2),
('What was the main cause of the Cold War?', 'Ideological conflict between US and USSR', 'Religious differences', 'Ideological conflict between US and USSR', 'Trade disputes', 2, 2),
('Who was the famous British explorer that mapped much of Australia?', 'James Cook', 'James Cook', 'Francis Drake', 'David Livingstone', 2, 2),
('What was the Boxer Rebellion?', 'Anti-foreigner uprising in China', 'Religious war in Europe', 'Anti-foreigner uprising in China', 'Civil war in Japan', 2, 2),
('Which country was formerly known as Ceylon?', 'Sri Lanka', 'India', 'Sri Lanka', 'Bangladesh', 2, 2),
('What was the Renaissance?', 'Cultural rebirth in Europe', 'A war', 'Cultural rebirth in Europe', 'Economic depression', 2, 2),
('Who was the first female Prime Minister of the UK?', 'Margaret Thatcher', 'Theresa May', 'Margaret Thatcher', 'Angela Merkel', 2, 2),
('Which battle marked the end of Napoleon’s reign?', 'Battle of Waterloo', 'Battle of Trafalgar', 'Battle of Leipzig', 'Battle of Waterloo', 2, 2),
('What was the Great Depression?', 'Worldwide economic downturn in 1930s', 'A war', 'Worldwide economic downturn in 1930s', 'A natural disaster', 2, 2),
('Who was the founder of the Mongol Empire?', 'Genghis Khan', 'Kublai Khan', 'Genghis Khan', 'Attila the Hun', 2, 2),
('Which event started the American Revolutionary War?', 'Battle of Lexington and Concord', 'Boston Tea Party', 'Battle of Lexington and Concord', 'Signing of the Declaration of Independence', 2, 2),
('Who was the leader of the Soviet Union during World War II?', 'Joseph Stalin', 'Vladimir Lenin', 'Joseph Stalin', 'Nikita Khrushchev', 2, 2),
('What was the purpose of the Marshall Plan?', 'Economic aid to rebuild Europe after WWII', 'Military alliance', 'Economic aid to rebuild Europe after WWII', 'Nuclear disarmament', 2, 2),
('Which empire built Machu Picchu?', 'Inca Empire', 'Aztec Empire', 'Maya Empire', 'Inca Empire', 2, 2),
('What was the role of the League of Nations?', 'Maintain world peace after WWI', 'Start WWII', 'Maintain world peace after WWI', 'Colonial expansion', 2, 2);

insert into Questions (questionText, correctAnswer, option1, option2, option3, diff_id, cat_id)
values
('What year did the Great Fire of London occur?', '1666', '1666', '1670', '1650', 3, 2),
('Who was the first ruler of the Holy Roman Empire?', 'Charlemagne', 'Charlemagne', 'Otto I', 'Frederick Barbarossa', 3, 2),
('What dynasty ruled China during the 14th century?', 'Ming', 'Tang', 'Ming', 'Qing', 3, 2),
('What battle ended Napoleon’s rule?', 'Battle of Waterloo', 'Battle of Leipzig', 'Battle of Waterloo', 'Battle of Trafalgar', 3, 2),
('What year did the French Revolution begin?', '1789', '1799', '1789', '1776', 3, 2),
('What was the name of the first successful English colony in America?', 'Jamestown', 'Plymouth', 'Jamestown', 'Roanoke', 3, 2),
('Who was the Ottoman Empire’s longest-reigning Sultan?', 'Suleiman the Magnificent', 'Suleiman the Magnificent', 'Mehmed II', 'Selim I', 3, 2),
('Which English king signed the Magna Carta?', 'King John', 'King Richard', 'King John', 'King Henry II', 3, 2),
('Who was the Emperor of Japan during World War II?', 'Hirohito', 'Meiji', 'Hirohito', 'Showa', 3, 2),
('What was the name of the German air force during World War II?', 'Luftwaffe', 'Wehrmacht', 'Luftwaffe', 'Kriegsmarine', 3, 2),
('Which treaty ended the Thirty Years’ War?', 'Peace of Westphalia', 'Treaty of Paris', 'Peace of Westphalia', 'Treaty of Utrecht', 3, 2),
('Who was the leader of the Soviet Union during the Cuban Missile Crisis?', 'Nikita Khrushchev', 'Joseph Stalin', 'Nikita Khrushchev', 'Leonid Brezhnev', 3, 2),
('Which event marked the start of the Protestant Reformation?', 'Martin Luther’s 95 Theses', 'Council of Trent', 'Martin Luther’s 95 Theses', 'Peace of Augsburg', 3, 2),
('What was the name of the ship on which the Pilgrims sailed to America?', 'Mayflower', 'Santa Maria', 'Mayflower', 'Endeavour', 3, 2),
('Which ancient civilization built the city of Petra?', 'Nabateans', 'Romans', 'Nabateans', 'Greeks', 3, 2),
('Who was the last pharaoh of Ancient Egypt?', 'Cleopatra', 'Nefertiti', 'Cleopatra', 'Hatshepsut', 3, 2),
('What was the primary cause of the War of the Roses?', 'Dynastic dispute', 'Religious conflict', 'Dynastic dispute', 'Territorial expansion', 3, 2),
('Which empire was ruled by Emperor Ashoka?', 'Maurya Empire', 'Gupta Empire', 'Maurya Empire', 'Mughal Empire', 3, 2),
('What was the main outcome of the Congress of Vienna?', 'Restoration of monarchies', 'Start of WWI', 'Restoration of monarchies', 'Establishment of United Nations', 3, 2),
('Who was the famous female ruler known as the “Virgin Queen”?', 'Elizabeth I', 'Mary Queen of Scots', 'Elizabeth I', 'Catherine the Great', 3, 2),
('Which battle was the turning point in the American Revolutionary War?', 'Battle of Saratoga', 'Battle of Yorktown', 'Battle of Saratoga', 'Battle of Bunker Hill', 3, 2),
('Who wrote the “Communist Manifesto”?', 'Karl Marx', 'Adam Smith', 'Karl Marx', 'Friedrich Engels', 3, 2),
('What was the significance of the Edict of Nantes?', 'Religious tolerance in France', 'Start of French Revolution', 'Religious tolerance in France', 'End of Thirty Years’ War', 3, 2),
('Who was the leader of the Haitian Revolution?', 'Toussaint Louverture', 'Simón Bolívar', 'Toussaint Louverture', 'Jean-Jacques Dessalines', 3, 2),
('What year did the Russian Revolution take place?', '1917', '1905', '1917', '1924', 3, 2);


--WrittenQuestions

-- Geography (cat_id=1), Easy (diff_id=1)
INSERT INTO WrittenQuestions (questionText, correctAnswer, diff_id, cat_id) VALUES
('What is the capital city of Spain?', 'Madrid', 1, 1),
('Which country is known for the Taj Mahal?', 'India', 1, 1),
('What is the largest continent by land area?', 'Asia', 1, 1),
('Which river flows through London?', 'Thames', 1, 1),
('What is the capital of Russia?', 'Moscow', 1, 1),
('Which country is famous for the Pyramids of Giza?', 'Egypt', 1, 1),
('What ocean lies east of the United States?', 'Atlantic Ocean', 1, 1),
('What is the capital city of China?', 'Beijing', 1, 1),
('Which continent is known as the "Dark Continent"?', 'Africa', 1, 1),
('What is the tallest waterfall in the world?', 'Angel Falls', 1, 1),
('Which country is home to the Kangaroo?', 'Australia', 1, 1),
('What is the capital of France?', 'Paris', 1, 1),
('Which mountain range includes Mount Everest?', 'Himalayas', 1, 1),
('What is the capital city of Mexico?', 'Mexico City', 1, 1),
('Which country is known as the "Land of the Midnight Sun"?', 'Norway', 1, 1),
('What is the largest island in the world?', 'Greenland', 1, 1),
('Which river is the longest in South America?', 'Amazon', 1, 1),
('What is the capital of South Africa?', 'Pretoria', 1, 1),
('Which country is famous for the Colosseum?', 'Italy', 1, 1),
('What is the name of the desert in Australia?', 'Great Victoria Desert', 1, 1),
('Which U.S. state is known as the "Lone Star State"?', 'Texas', 1, 1),
('What is the capital city of India?', 'New Delhi', 1, 1),
('Which ocean is to the south of Australia?', 'Southern Ocean', 1, 1),
('What is the capital of Argentina?', 'Buenos Aires', 1, 1),
('Which country is known for the statue Christ the Redeemer?', 'Brazil', 1, 1);

-- Geography (cat_id=1), Medium (diff_id=2)
INSERT INTO WrittenQuestions (questionText, correctAnswer, diff_id, cat_id) VALUES
('Which country has the most deserts in the world?', 'Australia', 2, 1),
('What is the capital of Peru?', 'Lima', 2, 1),
('Which river flows through Vienna?', 'Danube', 2, 1),
('What is the largest lake in Africa?', 'Lake Victoria', 2, 1),
('Which country is home to Mount Kilimanjaro?', 'Tanzania', 2, 1),
('What is the capital of Thailand?', 'Bangkok', 2, 1),
('Which island is shared by Indonesia, Malaysia, and Brunei?', 'Borneo', 2, 1),
('What is the longest river in North America?', 'Mississippi River', 2, 1),
('Which country is famous for the Matterhorn?', 'Switzerland', 2, 1),
('What is the capital of Chile?', 'Santiago', 2, 1),
('Which desert is located in South America?', 'Atacama Desert', 2, 1),
('What is the capital of Iceland?', 'Reykjavik', 2, 1),
('Which country is known for the Angel Falls?', 'Venezuela', 2, 1),
('What is the largest island in the Caribbean?', 'Cuba', 2, 1),
('Which river forms the border between South Africa and Zimbabwe?', 'Limpopo River', 2, 1),
('What is the capital of Nigeria?', 'Abuja', 2, 1),
('Which country is home to Lake Titicaca?', 'Bolivia', 2, 1),
('What is the highest mountain in South America?', 'Aconcagua', 2, 1),
('Which city is known as the "Pearl of the Orient"?', 'Hong Kong', 2, 1),
('What is the capital of Vietnam?', 'Hanoi', 2, 1),
('Which country is famous for the Serengeti National Park?', 'Tanzania', 2, 1),
('What is the largest island in Asia?', 'Borneo', 2, 1),
('Which river flows through Baghdad?', 'Tigris', 2, 1),
('What is the capital of Colombia?', 'Bogotá', 2, 1),
('Which country is known for the fjords of Patagonia?', 'Chile', 2, 1);

-- Geography (cat_id=1), Hard (diff_id=3)
INSERT INTO WrittenQuestions (questionText, correctAnswer, diff_id, cat_id) VALUES
('What is the capital of Mongolia?', 'Ulaanbaatar', 3, 1),
('What is the deepest point in the Pacific Ocean?', 'Mariana Trench', 3, 1),
('Which river is the longest in Australia?', 'Murray River', 3, 1),
('What is the capital of Suriname?', 'Paramaribo', 3, 1),
('Which country is home to the Salar de Uyuni salt flats?', 'Bolivia', 3, 1),
('What is the highest peak in the Alps?', 'Mont Blanc', 3, 1),
('Which country has the most active volcanoes?', 'Indonesia', 3, 1),
('What is the capital of Laos?', 'Vientiane', 3, 1),
('Which desert is the driest in the world?', 'Atacama Desert', 3, 1),
('What is the capital of Eritrea?', 'Asmara', 3, 1),
('Which country is home to the Great Rift Valley?', 'Kenya', 3, 1),
('What is the longest river in Southeast Asia?', 'Mekong River', 3, 1),
('Which island is known as the "Galapagos of the Indian Ocean"?', 'Socotra', 3, 1),
('What is the capital of Guyana?', 'Georgetown', 3, 1),
('Which country has the most extensive cave system in the world?', 'United States', 3, 1),
('What is the highest peak in Africa?', 'Kilimanjaro', 3, 1),
('Which country is home to the Namib Desert?', 'Namibia', 3, 1),
('What is the capital of Tajikistan?', 'Dushanbe', 3, 1),
('Which river flows through the Grand Canyon?', 'Colorado River', 3, 1),
('What is the capital of Brunei?', 'Bandar Seri Begawan', 3, 1),
('Which country is known for the Ha Long Bay?', 'Vietnam', 3, 1),
('What is the highest peak in North America?', 'Denali', 3, 1),
('Which country is home to the Okavango Delta?', 'Botswana', 3, 1),
('What is the capital of Vanuatu?', 'Port Vila', 3, 1);

-- History (cat_id=2), Easy (diff_id=1)
INSERT INTO WrittenQuestions (questionText, correctAnswer, diff_id, cat_id) VALUES
('Who was the first man to walk on the moon?', 'Neil Armstrong', 1, 2),
('In what year did the American Revolutionary War begin?', '1775', 1, 2),
('Which ancient civilization built the Colosseum?', 'Romans', 1, 2),
('Who was the first female Prime Minister of India?', 'Indira Gandhi', 1, 2),
('What year did World War I end?', '1918', 1, 2),
('Who discovered penicillin?', 'Alexander Fleming', 1, 2),
('Which country was ruled by Queen Elizabeth I?', 'England', 1, 2),
('What was the name of the ship sunk by an iceberg in 1912?', 'Titanic', 1, 2),
('Who was the famous leader of the American Civil Rights Movement?', 'Martin Luther King Jr.', 1, 2),
('Which war ended with the Treaty of Paris in 1783?', 'American Revolutionary War', 1, 2),
('Who invented the telephone?', 'Alexander Graham Bell', 1, 2),
('What was the name of the first human in space?', 'Yuri Gagarin', 1, 2),
('Which empire built the Great Wall of China?', 'Chinese Empire', 1, 2),
('Who was the leader of France during the French Revolution?', 'Louis XVI', 1, 2),
('What year did Christopher Columbus sail to the Americas?', '1492', 1, 2),
('Which country fought for independence from Britain in 1776?', 'United States', 1, 2),
('Who was the famous nurse during the American Civil War?', 'Clara Barton', 1, 2),
('What was the name of the first permanent English settlement in America?', 'Jamestown', 1, 2),
('Who was the first President of South Africa after apartheid?', 'Nelson Mandela', 1, 2),
('Which ancient civilization developed hieroglyphics?', 'Egyptians', 1, 2),
('What year did the Wright brothers achieve the first powered flight?', '1903', 1, 2),
('Who was the famous explorer who sailed around the world?', 'Ferdinand Magellan', 1, 2),
('Which war was fought between 1861 and 1865 in the United States?', 'Civil War', 1, 2),
('Who invented the steam engine?', 'James Watt', 1, 2),
('What was the name of the movement for women’s voting rights in the U.S.?', 'Suffrage Movement', 1, 2);

-- History (cat_id=2), Medium (diff_id=2)
INSERT INTO WrittenQuestions (questionText, correctAnswer, diff_id, cat_id) VALUES
('Who was the first Emperor of the French?', 'Napoleon Bonaparte', 2, 2),
('What year did the Spanish Armada attempt to invade England?', '1588', 2, 2),
('Which treaty ended the American Revolutionary War?', 'Treaty of Paris', 2, 2),
('Who was the leader of the Indian independence movement?', 'Mahatma Gandhi', 2, 2),
('What was the name of the ship that carried the first English settlers to Virginia?', 'Susan Constant', 2, 2),
('Which war was fought between Britain and Argentina in 1982?', 'Falklands War', 2, 2),
('Who was the first woman to win a Nobel Prize?', 'Marie Curie', 2, 2),
('What year did the Industrial Revolution begin in Britain?', '1760', 2, 2),
('Which civilization built the city of Machu Picchu?', 'Inca', 2, 2),
('Who was the leader of the Bolsheviks during the Russian Revolution?', 'Vladimir Lenin', 2, 2),
('What was the name of the battle that ended the American Civil War?', 'Battle of Appomattox', 2, 2),
('Which country was unified under Otto von Bismarck?', 'Germany', 2, 2),
('Who was the first African-American U.S. Supreme Court Justice?', 'Thurgood Marshall', 2, 2),
('What year did the Suez Crisis occur?', '1956', 2, 2),
('Which empire was ruled by Suleiman the Magnificent?', 'Ottoman Empire', 2, 2),
('What was the main goal of the Manhattan Project?', 'Develop the atomic bomb', 2, 2),
('Who was the British monarch during the American Revolutionary War?', 'George III', 2, 2),
('Which war was sparked by the assassination of Archduke Franz Ferdinand?', 'World War I', 2, 2),
('What was the name of the first artificial satellite?', 'Sputnik', 2, 2),
('Who led the Cuban Revolution in 1959?', 'Fidel Castro', 2, 2),
('What was the main cause of the Opium Wars?', 'Trade disputes over opium', 2, 2),
('Which country was the first to grant women the right to vote?', 'New Zealand', 2, 2),
('Who was the famous explorer who reached India by sea?', 'Vasco da Gama', 2, 2),
('What year did the Great Depression begin?', '1929', 2, 2),
('Which ancient civilization built the Parthenon?', 'Greeks', 2, 2);

-- History (cat_id=2), Hard (diff_id=3)
INSERT INTO WrittenQuestions (questionText, correctAnswer, diff_id, cat_id) VALUES
('What year was the Magna Carta signed?', '1215', 3, 2),
('Who was the first ruler of the Mughal Empire?', 'Babur', 3, 2),
('Which battle marked the end of the Hundred Years’ War?', 'Battle of Castillon', 3, 2),
('What was the name of the treaty that ended the War of the Spanish Succession?', 'Treaty of Utrecht', 3, 2),
('Who was the leader of the Taiping Rebellion?', 'Hong Xiuquan', 3, 2),
('What year did the Meiji Restoration begin in Japan?', '1868', 3, 2),
('Which civilization built the city of Tikal?', 'Maya', 3, 2),
('Who was the first female ruler of Russia?', 'Catherine the Great', 3, 2),
('What was the primary cause of the Boer Wars?', 'Control over diamond and gold resources', 3, 2),
('Which treaty ended the Seven Years’ War?', 'Treaty of Paris', 3, 2),
('Who was the leader of the Jacobites in the 1745 rebellion?', 'Charles Edward Stuart', 3, 2),
('What year did the Rwandan Genocide occur?', '1994', 3, 2),
('Which empire was ruled by Emperor Haile Selassie?', 'Ethiopian Empire', 3, 2),
('What was the name of the first nuclear-powered submarine?', 'USS Nautilus', 3, 2),
('Who was the architect of the unification of Italy?', 'Giuseppe Garibaldi', 3, 2),
('What was the main outcome of the Treaty of Tordesillas?', 'Divided the New World between Spain and Portugal', 3, 2),
('Which battle was the turning point of the Pacific Theater in World War II?', 'Battle of Midway', 3, 2),
('Who was the leader of the Khmer Rouge?', 'Pol Pot', 3, 2),
('What year did the Battle of Stalingrad begin?', '1942', 3, 2),
('Which ancient civilization developed cuneiform writing?', 'Sumerians', 3, 2),
('What was the name of the agreement that ended the American War of Independence?', 'Treaty of Paris', 3, 2),
('Who was the first ruler of the Achaemenid Persian Empire?', 'Cyrus the Great', 3, 2),
('What was the primary cause of the Sepoy Mutiny?', 'Cultural and religious grievances', 3, 2),
('Which battle ended the First Punic War?', 'Battle of the Aegates Islands', 3, 2),
('Who was the leader of the Mau Mau uprising in Kenya?', 'Dedan Kimathi', 3, 2);

-- Biology (cat_id=3), Easy (diff_id=1)
INSERT INTO WrittenQuestions (questionText, correctAnswer, diff_id, cat_id) VALUES
('What is the main source of energy for Earth’s climate system?', 'Sun', 1, 3),
('Which organ pumps blood throughout the body?', 'Heart', 1, 3),
('What gas do plants absorb during photosynthesis?', 'Carbon dioxide', 1, 3),
('What is the largest bone in the human body?', 'Femur', 1, 3),
('How many chambers does the human heart have?', 'Four', 1, 3),
('What is the basic unit of heredity?', 'Gene', 1, 3),
('Which part of the plant anchors it to the ground?', 'Root', 1, 3),
('What is the primary function of the small intestine?', 'Nutrient absorption', 1, 3),
('Which gas do humans primarily inhale?', 'Oxygen', 1, 3),
('What is the name of the process by which plants lose water?', 'Transpiration', 1, 3),
('Which organ is responsible for breathing?', 'Lungs', 1, 3),
('What is the main component of bones?', 'Calcium', 1, 3),
('Which part of the plant conducts photosynthesis?', 'Leaf', 1, 3),
('What is the largest organ inside the human body?', 'Liver', 1, 3),
('What is the name of the process by which cells divide?', 'Mitosis', 1, 3),
('Which blood cells carry oxygen?', 'Red blood cells', 1, 3),
('What is the main function of the large intestine?', 'Water absorption', 1, 3),
('Which organ controls the body’s balance?', 'Ear', 1, 3),
('What is the name of animals that eat only meat?', 'Carnivores', 1, 3),
('Which part of the eye allows light to enter?', 'Pupil', 1, 3),
('What is the study of plants called?', 'Botany', 1, 3),
('Which organ produces insulin?', 'Pancreas', 1, 3),
('What is the name of the outermost layer of a plant cell?', 'Cell wall', 1, 3),
('Which part of the brain controls breathing?', 'Medulla oblongata', 1, 3),
('What is the name of the sugar produced in photosynthesis?', 'Glucose', 1, 3);

-- Biology (cat_id=3), Medium (diff_id=2)
INSERT INTO WrittenQuestions (questionText, correctAnswer, diff_id, cat_id) VALUES
('What is the primary source of energy for cellular respiration?', 'Glucose', 2, 3),
('Which hormone regulates metabolism?', 'Thyroxine', 2, 3),
('What is the name of the process by which cells engulf particles?', 'Phagocytosis', 2, 3),
('Which part of the brain is responsible for memory?', 'Hippocampus', 2, 3),
('What is the largest species of fish?', 'Whale shark', 2, 3),
('Which vitamin is essential for vision?', 'Vitamin A', 2, 3),
('What is the name of the process by which plants convert light into energy?', 'Photosynthesis', 2, 3),
('Which organelle is responsible for cell division?', 'Centriole', 2, 3),
('What is the name of animals that eat both plants and animals?', 'Omnivores', 2, 3),
('Which blood vessel carries blood toward the heart?', 'Vein', 2, 3),
('What is the main function of the gall bladder?', 'Store bile', 2, 3),
('Which part of the plant transports water?', 'Xylem', 2, 3),
('What is the name of the protein that forms hair and nails?', 'Keratin', 2, 3),
('Which hormone is responsible for growth?', 'Growth hormone', 2, 3),
('What is the term for the movement of particles from high to low concentration?', 'Diffusion', 2, 3),
('Which organ is responsible for hearing?', 'Cochlea', 2, 3),
('What is the name of the molecule that stores energy in cells?', 'ATP', 2, 3),
('Which vitamin is necessary for bone health?', 'Vitamin D', 2, 3),
('What is the term for animals that lay eggs?', 'Oviparous', 2, 3),
('Which part of the cell contains genetic material?', 'Nucleus', 2, 3),
('What is the name of the process by which plants reproduce?', 'Pollination', 2, 3),
('Which organelle breaks down carbohydrates?', 'Amylase', 2, 3),
('What is the main function of the spleen?', 'Filter blood', 2, 3),
('Which type of cell is responsible for muscle contraction?', 'Muscle cell', 2, 3),
('What is the name of the process by which bacteria divide?', 'Binary fission', 2, 3);

-- Biology (cat_id=3), Hard (diff_id=3)
INSERT INTO WrittenQuestions (questionText, correctAnswer, diff_id, cat_id) VALUES
('What is the name of the enzyme that breaks down starch?', 'Amylase', 3, 3),
('Which organelle is responsible for detoxifying harmful substances?', 'Peroxisome', 3, 3),
('What is the term for the study of microscopic organisms?', 'Microbiology', 3, 3),
('Which molecule is the primary energy carrier in cells?', 'ATP', 3, 3),
('What is the name of the process by which RNA is synthesized?', 'Transcription', 3, 3),
('Which hormone regulates calcium levels in the blood?', 'Parathyroid hormone', 3, 3),
('What is the name of the structure that connects muscles to bones?', 'Tendon', 3, 3),
('Which organelle is responsible for lipid synthesis?', 'Smooth endoplasmic reticulum', 3, 3),
('What is the term for the genetic makeup of an organism?', 'Genotype', 3, 3),
('Which part of the brain regulates sleep?', 'Pineal gland', 3, 3),
('What is the name of the process by which plants convert nitrogen into usable compounds?', 'Nitrogen fixation', 3, 3),
('Which enzyme is responsible for DNA replication?', 'DNA polymerase', 3, 3),
('What is the term for the study of heredity?', 'Genetics', 3, 3),
('Which blood cells are involved in immune response?', 'Lymphocytes', 3, 3),
('What is the name of the molecule that carries genetic information in some viruses?', 'RNA', 3, 3),
('Which hormone is responsible for stress response?', 'Cortisol', 3, 3),
('What is the term for the process by which cells become specialized?', 'Differentiation', 3, 3),
('Which organelle is responsible for cellular digestion?', 'Lysosome', 3, 3),
('What is the name of the cycle that produces energy in mitochondria?', 'Krebs cycle', 3, 3),
('Which part of the plant is responsible for gas exchange?', 'Stomata', 3, 3),
('What is the term for the evolutionary process by which species adapt?', 'Natural selection', 3, 3),
('Which enzyme breaks down proteins in the stomach?', 'Pepsin', 3, 3),
('What is the name of the process by which cells repair DNA?', 'DNA repair', 3, 3),
('Which hormone regulates water balance in the body?', 'Antidiuretic hormone', 3, 3),
('What is the term for the study of ecosystems?', 'Ecology', 3, 3);

-- Movies (cat_id=4), Easy (diff_id=1)
INSERT INTO WrittenQuestions (questionText, correctAnswer, diff_id, cat_id) VALUES
('Who directed the movie "Jaws"?', 'Steven Spielberg', 1, 4),
('Which movie features the character "Simba"?', 'The Lion King', 1, 4),
('What is the name of the school in "Harry Potter"?', 'Hogwarts', 1, 4),
('Who played Captain America in the Marvel Cinematic Universe?', 'Chris Evans', 1, 4),
('Which movie is about a clownfish searching for his son?', 'Finding Nemo', 1, 4),
('What is the name of the ogre in "Shrek"?', 'Shrek', 1, 4),
('Which movie features the song "Hakuna Matata"?', 'The Lion King', 1, 4),
('Who is the superhero alter ego of Tony Stark?', 'Iron Man', 1, 4),
('Which animated movie is set in the city of Zootopia?', 'Zootopia', 1, 4),
('What is the name of the ship in "Pirates of the Caribbean"?', 'Black Pearl', 1, 4),
('Who directed "Star Wars: Episode IV – A New Hope"?', 'George Lucas', 1, 4),
('Which movie features a character named Woody?', 'Toy Story', 1, 4),
('What is the name of the princess in "The Princess and the Frog"?', 'Tiana', 1, 4),
('Which movie is set in a world where dreams can be infiltrated?', 'Inception', 1, 4),
('Who played Hermione Granger in the Harry Potter series?', 'Emma Watson', 1, 4),
('Which animated movie features a dragon named Mushu?', 'Mulan', 1, 4),
('What is the name of the villain in "The Little Mermaid"?', 'Ursula', 1, 4),
('Which movie features the quote "Life is like a box of chocolates"?', 'Forrest Gump', 1, 4),
('Who directed "E.T. the Extra-Terrestrial"?', 'Steven Spielberg', 1, 4),
('Which movie is about a young boy who befriends an alien?', 'E.T. the Extra-Terrestrial', 1, 4),
('What is the name of the lion in "The Chronicles of Narnia"?', 'Aslan', 1, 4),
('Which movie features a character named Darth Vader?', 'Star Wars', 1, 4),
('Who played Spider-Man in "Spider-Man: Homecoming"?', 'Tom Holland', 1, 4),
('Which animated movie is about a rat who loves to cook?', 'Ratatouille', 1, 4),
('What is the name of the wizard in "The Lord of the Rings"?', 'Gandalf', 1, 4);

-- Movies (cat_id=4), Medium (diff_id=2)
INSERT INTO WrittenQuestions (questionText, correctAnswer, diff_id, cat_id) VALUES
('Who directed "Kill Bill: Volume 1"?', 'Quentin Tarantino', 2, 4),
('What is the name of the fictional African country in "Black Panther"?', 'Wakanda', 2, 4),
('Which actor played the role of Neo in "The Matrix"?', 'Keanu Reeves', 2, 4),
('What is the name of the prison in "The Green Mile"?', 'Cold Mountain Penitentiary', 2, 4),
('Who composed the score for "Jurassic Park"?', 'John Williams', 2, 4),
('Which movie features the character "Ellen Ripley"?', 'Alien', 2, 4),
('What is the name of the fictional island in "Jurassic Park"?', 'Isla Nublar', 2, 4),
('Who played the role of Katniss Everdeen in "The Hunger Games"?', 'Jennifer Lawrence', 2, 4),
('Which movie is set in the world of Pandora?', 'Avatar', 2, 4),
('What is the name of the director of "Inglourious Basterds"?', 'Quentin Tarantino', 2, 4),
('Which actor portrayed Captain Jack Sparrow?', 'Johnny Depp', 2, 4),
('What is the name of the AI in "The Terminator"?', 'Skynet', 2, 4),
('Which movie features the song "I Will Always Love You"?', 'The Bodyguard', 2, 4),
('Who directed "The Big Lebowski"?', 'Coen Brothers', 2, 4),
('What is the name of the main character in "Mad Max: Fury Road"?', 'Max Rockatansky', 2, 4),
('Which actress played Rey in "Star Wars: The Force Awakens"?', 'Daisy Ridley', 2, 4),
('What is the name of the hotel in "Home Alone"?', 'Plaza Hotel', 2, 4),
('Which movie features a character named Maximus Decimus Meridius?', 'Gladiator', 2, 4),
('Who directed "Moonlight"?', 'Barry Jenkins', 2, 4),
('What is the name of the villain in "The Avengers"?', 'Loki', 2, 4),
('Which movie is about a group of superheroes called the Guardians?', 'Guardians of the Galaxy', 2, 4),
('Who played the role of Andy Dufresne in "The Shawshank Redemption"?', 'Tim Robbins', 2, 4),
('What is the name of the fictional school in "Dead Poets Society"?', 'Welton Academy', 2, 4),
('Which movie features the quote "There’s no place like home"?', 'The Wizard of Oz', 2, 4),
('Who directed "Spirited Away"?', 'Hayao Miyazaki', 2, 4);

-- Movies (cat_id=4), Hard (diff_id=3)
INSERT INTO WrittenQuestions (questionText, correctAnswer, diff_id, cat_id) VALUES
('Who directed the 1960 film "Psycho"?', 'Alfred Hitchcock', 3, 4),
('What is the name of the composer for "The Good, the Bad and the Ugly"?', 'Ennio Morricone', 3, 4),
('Which film won the Oscar for Best Picture in 1972?', 'The Godfather', 3, 4),
('What is the name of the main character in "There Will Be Blood"?', 'Daniel Plainview', 3, 4),
('Who directed the film "Seven Samurai"?', 'Akira Kurosawa', 3, 4),
('What is the name of the fictional newspaper in "Citizen Kane"?', 'The Inquirer', 3, 4),
('Which actor played the role of Travis Bickle in "Taxi Driver"?', 'Robert De Niro', 3, 4),
('What is the name of the director of "Amélie"?', 'Jean-Pierre Jeunet', 3, 4),
('Which film features a character named Keyser Söze?', 'The Usual Suspects', 3, 4),
('What is the name of the ship in "Apocalypse Now"?', 'Erebus', 3, 4),
('Who played the role of Scarlett O’Hara in "Gone with the Wind"?', 'Vivien Leigh', 3, 4),
('Which film is set in the fictional dystopian city of Los Angeles 2019?', 'Blade Runner', 3, 4),
('What is the name of the director of "Chinatown"?', 'Roman Polanski', 3, 4),
('Which movie features the character "Randle McMurphy"?', 'One Flew Over the Cuckoo’s Nest', 3, 4),
('What is the name of the composer for "Schindler’s List"?', 'John Williams', 3, 4),
('Which film is known for the quote "I’m walking here!"?', 'Midnight Cowboy', 3, 4),
('Who directed the film "Parasite"?', 'Bong Joon-ho', 3, 4),
('What is the name of the main character in "The Graduate"?', 'Benjamin Braddock', 3, 4),
('Which film is set in the fictional town of Hill Valley?', 'Back to the Future', 3, 4),
('Who played the role of Rick Blaine in "Casablanca"?', 'Humphrey Bogart', 3, 4),
('What is the name of the director of "Bicycle Thieves"?', 'Vittorio De Sica', 3, 4),
('Which film features the character "Vito Corleone"?', 'The Godfather', 3, 4),
('What is the name of the prison in "Cool Hand Luke"?', 'Road Prison 36', 3, 4),
('Who directed the film "12 Angry Men"?', 'Sidney Lumet', 3, 4),
('Which film is known for the quote "You can’t handle the truth!"?', 'A Few Good Men', 3, 4);

-- Geography (cat_id=1), Easy (diff_id=1)
INSERT INTO MultipleChoiceQuestion (questionText, correctAnswer, option1, option2, option3, diff_id, cat_id) VALUES
('Which countries are known for their coral reefs?', 'Australia;Maldives', 'Australia', 'Maldives', 'Sweden', 1, 1),
('Which cities are capitals of Asian nations?', 'Tokyo;Seoul', 'Tokyo', 'Seoul', 'Dubai', 1, 1),
('Which oceans border Africa?', 'Atlantic Ocean;Indian Ocean', 'Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean', 1, 1),
('Which animals are native to South America?', 'Capybara;Andean Condor', 'Capybara', 'Andean Condor', 'Panda', 1, 1),
('Which rivers flow through European capitals?', 'Thames;Tiber', 'Thames', 'Tiber', 'Ganges', 1, 1),
('Which countries are famous for their ancient temples?', 'Cambodia;India', 'Cambodia', 'India', 'Norway', 1, 1),
('Which continents have major deserts?', 'Africa;Asia', 'Africa', 'Asia', 'Europe', 1, 1),
('Which cities are known for their bridges?', 'Lisbon;San Francisco', 'Lisbon', 'San Francisco', 'Phoenix', 1, 1),
('Which countries are in the Baltic region?', 'Estonia;Latvia', 'Estonia', 'Latvia', 'Greece', 1, 1),
('Which mountain ranges are in South America?', 'Andes;Patagonian', 'Andes', 'Patagonian', 'Himalayas', 1, 1);

-- Geography (cat_id=1), Medium (diff_id=2)
INSERT INTO MultipleChoiceQuestion (questionText, correctAnswer, option1, option2, option3, diff_id, cat_id) VALUES
('Which countries share the Tigris River?', 'Iraq;Turkey', 'Iraq', 'Turkey', 'Iran', 1, 1),
('Which islands are in Polynesia?', 'Tonga;Samoa', 'Tonga', 'Samoa', 'Iceland', 2, 1),
('Which cities are capitals of Central American nations?', 'San José;Panama City', 'San José', 'Panama City', 'Havana', 2, 1),
('Which lakes are in North America?', 'Huron;Ontario', 'Huron', 'Ontario', 'Titicaca', 2, 1),
('Which countries have tundra ecosystems?', 'Canada;Russia', 'Canada', 'Russia', 'Brazil', 2, 1),
('Which rivers flow through Southeast Asia?', 'Mekong;Irrawaddy', 'Mekong', 'Irrawaddy', 'Nile', 2, 1),
('Which countries are known for their wetlands?', 'Botswana;Vietnam', 'Botswana', 'Vietnam', 'Germany', 2, 1),
('Which mountain ranges are in Africa?', 'Atlas;Drakensberg', 'Atlas', 'Drakensberg', 'Rockies', 2, 1),
('Which straits connect oceans?', 'Bosporus;Dardanelles', 'Bosporus', 'Dardanelles', 'Panama Canal', 2, 1),
('Which countries are in the Andes region?', 'Ecuador;Bolivia', 'Ecuador', 'Bolivia', 'Chile', 2, 1);

-- Geography (cat_id=1), Hard (diff_id=3)
INSERT INTO MultipleChoiceQuestion (questionText, correctAnswer, option1, option2, option3, diff_id, cat_id) VALUES
('Which countries have subarctic climates?', 'Finland;Alaska', 'Finland', 'Alaska', 'India', 3, 1),
('Which rivers are in East Africa?', 'Nile;Zambezi', 'Nile', 'Zambezi', 'Amazon', 3, 1),
('Which islands are in the Indian Ocean?', 'Andaman;Zanzibar', 'Andaman', 'Zanzibar', 'Falklands', 3, 1),
('Which countries share the Karakum Desert?', 'Turkmenistan;Uzbekistan', 'Turkmenistan', 'Uzbekistan', 'Kazakhstan', 3, 1),
('Which peaks are the highest in Europe?', 'Elbrus;Mont Blanc', 'Elbrus', 'Mont Blanc', 'Kilimanjaro', 3, 1),
('Which countries have salt lakes?', 'Iran;Turkey', 'Iran', 'Turkey', 'Japan', 3, 1),
('Which lakes are in Asia?', 'Caspian Sea;Aral Sea', 'Caspian Sea', 'Aral Sea', 'Baikal', 3, 1),
('Which countries have limestone caves?', 'Slovenia;Vietnam', 'Slovenia', 'Vietnam', 'Canada', 3, 1),
('Which oceanic currents influence climate?', 'Gulf Stream;Kuroshio', 'Gulf Stream', 'Kuroshio', 'El Ni?o', 3, 1),
('Which regions have permafrost?', 'Siberia;Nunavut', 'Siberia', 'Nunavut', 'Sahara', 3, 1);

-- History (cat_id=2), Easy (diff_id=1)
INSERT INTO MultipleChoiceQuestion (questionText, correctAnswer, option1, option2, option3, diff_id, cat_id) VALUES
('Which explorers discovered new routes?', 'Ferdinand Magellan;Zheng He', 'Ferdinand Magellan', 'Zheng He', 'Napoleon', 1, 2),
('Which monarchs ruled France?', 'Louis XIV;Napoleon I', 'Louis XIV', 'Napoleon I', 'Cleopatra', 1, 2),
('Which wars involved France?', 'Napoleonic Wars;Franco-Prussian War', 'Napoleonic Wars', 'Franco-Prussian War', 'Trojan War', 1, 2),
('Which figures led abolition movements?', 'Frederick Douglass;Harriet Tubman', 'Frederick Douglass', 'Harriet Tubman', 'Joan of Arc', 1, 2),
('Which treaties ended wars?', 'Treaty of Ghent;Treaty of Tordesillas', 'Treaty of Ghent', 'Treaty of Tordesillas', 'Edict of Milan', 1, 2),
('Which inventors created machines?', 'Eli Whitney;Thomas Edison', 'Eli Whitney', 'Thomas Edison', 'Galileo', 1, 2),
('Which empires ruled Europe?', 'Habsburg Empire;Holy Roman Empire', 'Habsburg Empire', 'Holy Roman Empire', 'Maya Empire', 1, 2),
('Which events marked exploration?', 'Columbus’ Voyage;Cook’s Expeditions', 'Columbus’ Voyage', 'Cook’s Expeditions', 'Fall of Rome', 1, 2),
('Which leaders fought for equality?', 'Sojourner Truth;Malcolm X', 'Sojourner Truth', 'Malcolm X', 'Hannibal', 1, 2);

-- History (cat_id=2), Medium (diff_id=2)
INSERT INTO MultipleChoiceQuestion (questionText, correctAnswer, option1, option2, option3, diff_id, cat_id) VALUES
('Which leaders shaped modern Europe?', 'Cavour;Mazzini', 'Cavour', 'Mazzini', 'Aristotle', 2, 2),
('Which treaties ended revolutions?', 'Congress of Vienna;Treaty of Nanjing', 'Congress of Vienna', 'Treaty of Nanjing', 'Magna Carta', 2, 2),
('Which figures led anti-colonial movements?', 'Ho Chi Minh;Kwame Nkrumah', 'Ho Chi Minh', 'Kwame Nkrumah', 'Nero', 2, 2),
('Which wars involved Asia?', 'Sino-Japanese War;Russo-Japanese War', 'Sino-Japanese War', 'Russo-Japanese War', 'Punic Wars', 2, 2),
('Which scientists studied chemistry?', 'Dmitri Mendeleev;Marie Curie', 'Dmitri Mendeleev', 'Marie Curie', 'Drake', 2, 2),
('Which events involved rebellions?', 'Taiping Rebellion;Indian Mutiny', 'Taiping Rebellion', 'Indian Mutiny', 'Battle of Waterloo', 2, 2),
('Which monarchs ruled during transitions?', 'Queen Isabella;Franz Joseph', 'Queen Isabella', 'Franz Joseph', 'Ramses II', 2, 2),
('Which thinkers influenced democracy?', 'Montesquieu;Mill', 'Montesquieu', 'Mill', 'Vercingetorix', 2, 2),
('Which countries were in the Warsaw Pact?', 'Poland;Hungary', 'Poland', 'Hungary', 'Brazil', 2, 2);

-- History (cat_id=2), Hard (diff_id=3)
INSERT INTO MultipleChoiceQuestion (questionText, correctAnswer, option1, option2, option3, diff_id, cat_id) VALUES
('Which battles shaped ancient history?', 'Thermopylae;Gaugamela', 'Thermopylae', 'Gaugamela', 'Stalingrad', 3, 2),
('Which treaties ended feudal conflicts?', 'Peace of Lodi;Treaty of Constance', 'Peace of Lodi', 'Treaty of Constance', 'Treaty of Paris', 3, 2),
('Which rulers centralized power?', 'Ivan III;Kublai Khan', 'Ivan III', 'Kublai Khan', 'Socrates', 3, 2),
('Which events marked intellectual shifts?', 'Islamic Golden Age;Song Dynasty', 'Islamic Golden Age', 'Song Dynasty', 'French Revolution', 3, 2),
('Which figures led schisms?', 'Zwingli;Erasmus', 'Zwingli', 'Erasmus', 'Caligula', 3, 2),
('Which civilizations built observatories?', 'Chavín;Chacoan', 'Chavín', 'Chacoan', 'Mongols', 3, 2),
('Which scientists studied mechanics?', 'Archimedes;Bernoulli', 'Archimedes', 'Bernoulli', 'Einstein', 3, 2),
('Which years saw artifact discoveries?', '1799;1974', '1799', '1974', '1000', 3, 2),
('Which empires controlled Southeast Asia?', 'Khmer Empire;Srivijaya', 'Khmer Empire', 'Srivijaya', 'Inca Empire', 3, 2),
('Which leaders enacted land reforms?', 'Cleisthenes;Stein', 'Cleisthenes', 'Stein', 'Gandhi', 3, 2);

-- Biology (cat_id=3), Easy (diff_id=1)
INSERT INTO MultipleChoiceQuestion (questionText, correctAnswer, option1, option2, option3, diff_id, cat_id) VALUES
('Which organs process nutrients?', 'Intestines;Stomach', 'Intestines', 'Stomach', 'Lungs', 1, 3),
('Which animals are reptiles?', 'Turtles;Lizards', 'Turtles', 'Lizards', 'Bats', 1, 3),
('Which plant parts store energy?', 'Roots;Bulbs', 'Roots', 'Bulbs', 'Leaves', 1, 3),
('Which nutrients support immunity?', 'Zinc;Vitamin D', 'Zinc', 'Vitamin D', 'Sodium', 1, 3),
('Which organs regulate temperature?', 'Skin;Hypothalamus', 'Skin', 'Hypothalamus', 'Kidneys', 1, 3),
('Which bones form joints?', 'Femur;Humerus', 'Femur', 'Humerus', 'Heart', 1, 3),
('Which molecules form membranes?', 'Phospholipids;Cholesterol', 'Phospholipids', 'Cholesterol', 'Sugar', 1, 3),
('Which plant parts produce pollen?', 'Anthers;Stamens', 'Anthers', 'Stamens', 'Pistil', 1, 3),
('Which organs produce urine?', 'Kidneys;Bladder', 'Kidneys', 'Bladder', 'Liver', 1, 3),
('Which vitamins aid bone health?', 'Vitamin D;Vitamin K', 'Vitamin D', 'Vitamin K', 'Vitamin B6', 1, 3);

-- Biology (cat_id=3), Medium (diff_id=2)
INSERT INTO MultipleChoiceQuestion (questionText, correctAnswer, option1, option2, option3, diff_id, cat_id) VALUES
('Which hormones regulate sleep?', 'Melatonin;Cortisol', 'Melatonin', 'Cortisol', 'Insulin', 2, 3),
('Which structures protect plants?', 'Cuticle;Epidermis', 'Cuticle', 'Epidermis', 'Phloem', 2, 3),
('Which animals use camouflage?', 'Cuttlefish;Stick Insects', 'Cuttlefish', 'Stick Insects', 'Tigers', 2, 3),
('Which proteins bind oxygen?', 'Hemoglobin;Myoglobin', 'Hemoglobin', 'Myoglobin', 'Actin', 2, 3),
('Which organelles store materials?', 'Vacuoles;Vesicles', 'Vacuoles', 'Vesicles', 'Nucleus', 2, 3),
('Which vitamins aid nerve function?', 'Vitamin B1;Vitamin B6', 'Vitamin B1', 'Vitamin B6', 'Vitamin C', 2, 3),
('Which processes repair tissues?', 'Mitosis;Regeneration', 'Mitosis', 'Regeneration', 'Respiration', 2, 3),
('Which cells produce hormones?', 'Endocrine Cells;Pituitary Cells', 'Endocrine Cells', 'Pituitary Cells', 'Red Blood Cells', 2, 3),
('Which enzymes digest starches?', 'Amylase;Maltase', 'Amylase', 'Maltase', 'Lipase', 2, 3),
('Which molecules signal immunity?', 'Antibodies;Cytokines', 'Antibodies', 'Cytokines', 'Glucose', 2, 3);

-- Biology (cat_id=3), Hard (diff_id=3)
INSERT INTO MultipleChoiceQuestion (questionText, correctAnswer, option1, option2, option3, diff_id, cat_id) VALUES
('Which enzymes regulate metabolism?', 'Kinases;Phosphatases', 'Kinases', 'Phosphatases', 'Protease', 3, 3),
('Which organelles synthesize lipids?', 'Smooth ER;Golgi Apparatus', 'Smooth ER', 'Golgi Apparatus', 'Lysosome', 3, 3),
('Which molecules control development?', 'Hox Genes;Growth Factors', 'Hox Genes', 'Growth Factors', 'Salt', 3, 3),
('Which processes maintain diversity?', 'Recombination;Mutation', 'Recombination', 'Mutation', 'Weathering', 3, 3),
('Which cells mediate allergies?', 'Mast Cells;Basophils', 'Mast Cells', 'Basophils', 'Platelets', 3, 3),
('Which hormones regulate sodium?', 'Aldosterone;ADH', 'Aldosterone', 'ADH', 'Estrogen', 3, 3),
('Which pathways produce ATP?', 'ETC;Fermentation', 'ETC', 'Fermentation', 'Glycolysis', 3, 3),
('Which structures regulate turgor?', 'Tonoplast;Cell Wall', 'Tonoplast', 'Cell Wall', 'Stomata', 3, 3),
('Which processes cycle phosphorus?', 'Runoff;Sedimentation', 'Runoff', 'Sedimentation', 'Nitrification', 3, 3),
('Which molecules fight viruses?', 'Interferons;Complement Proteins', 'Interferons', 'Complement Proteins', 'Lipids', 3, 3);

-- Movies (cat_id=4), Easy (diff_id=1)
INSERT INTO MultipleChoiceQuestion (questionText, correctAnswer, option1, option2, option3, diff_id, cat_id) VALUES
('Which animated films feature families?', 'Coco;Onward', 'Coco', 'Onward', 'Inception', 1, 4),
('Which superheroes are in DC films?', 'Aquaman;Flash', 'Aquaman', 'Flash', 'Iron Man', 1, 4),
('Which directors made family films?', 'Chris Buck;Jennifer Lee', 'Chris Buck', 'Jennifer Lee', 'Tarantino', 1, 4),
('Which characters are Pixar heroes?', 'Woody;Remy', 'Woody', 'Remy', 'Voldemort', 1, 4),
('Which movies involve adventures?', 'Up;Toy Story', 'Up', 'Toy Story', 'Titanic', 1, 4),
('Which songs are in animated films?', 'Colors of the Wind;Be Our Guest', 'Colors of the Wind', 'Be Our Guest', 'My Heart Will Go On', 1, 4),
('Which actors played princesses?', 'Emma Watson;Lily James', 'Emma Watson', 'Lily James', 'Tom Cruise', 1, 4),
('Which films feature animals?', 'Bambi;Dumbo', 'Bambi', 'Dumbo', 'The Matrix', 1, 4),
('Which villains are in Disney films?', 'Jafar;Gaston', 'Jafar', 'Gaston', 'Loki', 1, 4),
('Which movies are set in cities?', 'Zootopia;Big Hero 6', 'Zootopia', 'Big Hero 6', 'The Godfather', 1, 4);

-- Movies (cat_id=4), Medium (diff_id=2)
INSERT INTO MultipleChoiceQuestion (questionText, correctAnswer, option1, option2, option3, diff_id, cat_id) VALUES
('Which directors made dramas?', 'Ang Lee;Alfonso Cuarón', 'Ang Lee', 'Alfonso Cuarón', 'John Ford', 2, 4),
('Which movies feature quests?', 'The Green Knight;Willow', 'The Green Knight', 'Willow', 'Coco', 2, 4),
('Which actors played rebels?', 'Christian Bale;Heath Ledger', 'Christian Bale', 'Heath Ledger', 'Chris Pratt', 2, 4),
('Which films involve mysteries?', 'Knives Out;Gone Girl', 'Knives Out', 'Gone Girl', 'Moana', 2, 4),
('Which characters are in comedies?', 'Dory;Olaf', 'Dory', 'Olaf', 'Darth Vader', 2, 4),
('Which movies are set in deserts?', 'Mad Max;Lawrence of Arabia', 'Mad Max', 'Lawrence of Arabia', 'Zootopia', 2, 4),
('Which villains are in fantasy films?', 'Sauron;Voldemort', 'Sauron', 'Voldemort', 'Maleficent', 2, 4),
('Which songs are in film soundtracks?', 'Shallow;Skyfall', 'Shallow', 'Skyfall', 'Let It Go', 2, 4),
('Which animated films explore emotions?', 'Turning Red;Inside Out', 'Turning Red', 'Inside Out', 'Fight Club', 2, 4),
('Which movies involve betrayals?', 'Gladiator;The Departed', 'Gladiator', 'The Departed', 'Toy Story', 2, 4);

-- Movies (cat_id=4), Hard (diff_id=3)
INSERT INTO MultipleChoiceQuestion (questionText, correctAnswer, option1, option2, option3, diff_id, cat_id) VALUES
('Which directors made art films?', 'Wong Kar-wai;Apichatpong Weerasethakul', 'Wong Kar-wai', 'Apichatpong Weerasethakul', 'Disney', 3, 4),
('Which movies feature surrealism?', 'Mulholland Drive;Eternal Sunshine', 'Mulholland Drive', 'Eternal Sunshine', 'Titanic', 3, 4),
('Which actors played antiheroes?', 'Daniel Day-Lewis;Joaquin Phoenix', 'Daniel Day-Lewis', 'Joaquin Phoenix', 'Tom Holland', 3, 4),
('Which films involve paradoxes?', 'Predestination;Donnie Darko', 'Predestination', 'Donnie Darko', 'Coco', 3, 4),
('Which composers scored epics?', 'Max Richter;Alexandre Desplat', 'Max Richter', 'Alexandre Desplat', 'Paul McCartney', 3, 4),
('Which movies are dystopian?', 'Children of Men;Brazil', 'Children of Men', 'Brazil', 'Finding Nemo', 3, 4),
('Which characters are in indie films?', 'Clementine;Joel', 'Clementine', 'Joel', 'Buzz Lightyear', 3, 4),
('Which animated films have dark themes?', 'Perfect Blue;Spirited Away', 'Perfect Blue', 'Spirited Away', 'The Incredibles', 3, 4),
('Which movies feature moral dilemmas?', 'A Separation;Leviathan', 'A Separation', 'Leviathan', 'Shrek', 3, 4),
('Which films involve historical tragedies?', 'The Pianist;Schindler’s List', 'The Pianist', 'Schindler’s List', 'Up', 3, 4);

-- Geography (cat_id=1), Easy (diff_id=1)
INSERT INTO TrueFalseQuestions (questionText, correctAnswer, diff_id, cat_id) VALUES
('The capital of Portugal is Lisbon.', 1, 1, 1),
('The Black Sea is located in South America.', 0, 1, 1),
('Sweden is a Nordic country.', 1, 1, 1),
('The Alps are in Africa.', 0, 1, 1),
('The island of Bali is part of Indonesia.', 1, 1, 1),
('The equator passes through France.', 0, 1, 1),
('The Caribbean Sea is near Jamaica.', 1, 1, 1),
('Alaska is a country in North America.', 0, 1, 1),
('The city of Dubai is in the United Arab Emirates.', 1, 1, 1),
('Greenland is larger than Australia.', 0, 1, 1),
('The capital of Greece is Athens.', 1, 1, 1),
('The Red Sea is west of India.', 0, 1, 1),
('Fiji is an island nation in the Pacific Ocean.', 1, 1, 1),
('The capital of Turkey is Istanbul.', 0, 1, 1),
('The Pyrenees Mountains separate Spain and France.', 1, 1, 1),
('The continent of Australia is also a country.', 1, 1, 1),
('The capital of South Korea is Seoul.', 1, 1, 1),
('The Arctic Circle is in the Southern Hemisphere.', 0, 1, 1),
('The island of Madagascar is off the coast of Africa.', 1, 1, 1),
('The capital of Denmark is Oslo.', 0, 1, 1),
('The Dead Sea is between Israel and Jordan.', 1, 1, 1),
('The Pacific Ocean is the smallest ocean.', 0, 1, 1),
('The capital of Poland is Warsaw.', 1, 1, 1),
('The Bahamas are in the Atlantic Ocean.', 1, 1, 1),
('The capital of Morocco is Casablanca.', 0, 1, 1);

-- Geography (cat_id=1), Medium (diff_id=2)
INSERT INTO TrueFalseQuestions (questionText, correctAnswer, diff_id, cat_id) VALUES
('The capital of Ghana is Accra.', 1, 2, 1),
('The Ural Mountains are in South America.', 0, 2, 1),
('The island of Tasmania is part of Australia.', 1, 2, 1),
('The capital of Mongolia is Ulan Bator.', 1, 2, 1),
('The Yucatán Peninsula is in Mexico.', 1, 2, 1),
('The capital of Algeria is Tunis.', 0, 2, 1),
('The Coral Sea is near Papua New Guinea.', 1, 2, 1),
('The capital of Sri Lanka is Colombo.', 1, 2, 1),
('The Gobi Desert is in Europe.', 0, 2, 1),
('The capital of Ecuador is Quito.', 1, 2, 1),
('The Bering Strait separates Russia and Alaska.', 1, 2, 1),
('The capital of Latvia is Tallinn.', 0, 2, 1),
('The island of Sumatra is part of Indonesia.', 1, 2, 1),
('The capital of Uruguay is Montevideo.', 1, 2, 1),
('The Bay of Bengal is west of India.', 0, 2, 1),
('The capital of Oman is Muscat.', 1, 2, 1),
('The Kamchatka Peninsula is in Russia.', 1, 2, 1),
('The capital of Finland is Stockholm.', 0, 2, 1),
('The island of Mauritius is in the Indian Ocean.', 1, 2, 1),
('The capital of Costa Rica is San José.', 1, 2, 1),
('The Sonoran Desert is in Asia.', 0, 2, 1),
('The capital of Jamaica is Kingston.', 1, 2, 1),
('The Tibetan Plateau is in China.', 1, 2, 1),
('The capital of Paraguay is Asunción.', 1, 2, 1),
('The Gulf of Mexico is east of California.', 0, 2, 1);

-- Geography (cat_id=1), Hard (diff_id=3)
INSERT INTO TrueFalseQuestions (questionText, correctAnswer, diff_id, cat_id) VALUES
('The capital of Burundi is Gitega.', 1, 3, 1),
('The Kuril Islands are part of Canada.', 0, 3, 1),
('The Atoll of Palmyra is a U.S. territory.', 1, 3, 1),
('The capital of Seychelles is Victoria.', 1, 3, 1),
('The Altiplano Plateau is in Bolivia.', 1, 3, 1),
('The capital of Eswatini is Mbabane.', 1, 3, 1),
('The Chagos Archipelago is in the Pacific Ocean.', 0, 3, 1),
('The capital of Benin is Porto-Novo.', 1, 3, 1),
('The Nullarbor Plain is in Australia.', 1, 3, 1),
('The capital of Timor-Leste is Dili.', 1, 3, 1),
('The Taklamakan Desert is in China.', 1, 3, 1),
('The capital of Comoros is Moroni.', 1, 3, 1),
('The Faroe Islands are part of Denmark.', 1, 3, 1),
('The capital of Nauru is Yaren.', 1, 3, 1),
('The Deccan Plateau is in Brazil.', 0, 3, 1),
('The capital of Sao Tomé and Príncipe is Sao Tomé.', 1, 3, 1),
('The Drakensberg Mountains are in South Africa.', 1, 3, 1),
('The capital of Tonga is Nuku?alofa.', 1, 3, 1),
('The Kerguelen Islands are in the Indian Ocean.', 1, 3, 1),
('The capital of Lesotho is Maseru.', 1, 3, 1),
('The Qattara Depression is in Egypt.', 1, 3, 1),
('The capital of Vanuatu is Port Vila.', 1, 3, 1),
('The Patagonian Desert is in Argentina.', 1, 3, 1),
('The capital of Djibouti is Djibouti City.', 1, 3, 1),
('The Spratly Islands are in the Mediterranean Sea.', 0, 3, 1);

-- History (cat_id=2), Easy (diff_id=1)
INSERT INTO TrueFalseQuestions (questionText, correctAnswer, diff_id, cat_id) VALUES
('The Industrial Revolution began in the 18th century.', 1, 1, 2),
('The Roman Empire fell in the 20th century.', 0, 1, 2),
('The Wright brothers invented the airplane.', 1, 1, 2),
('The French Revolution occurred in the 17th century.', 0, 1, 2),
('The Battle of Hastings was in 1066.', 1, 1, 2),
('The Renaissance began in Asia.', 0, 1, 2),
('The Magna Carta was signed in England.', 1, 1, 2),
('The Vikings originated from South America.', 0, 1, 2),
('The Suez Canal opened in 1869.', 1, 1, 2),
('The Black Death was a war in Europe.', 0, 1, 2),
('The Spanish Inquisition targeted heretics.', 1, 1, 2),
('The Apollo 11 mission landed on Mars.', 0, 1, 2),
('The Silk Road connected Europe and Asia.', 1, 1, 2),
('The Cold War was fought with battles.', 0, 1, 2),
('The Panama Canal was completed in 1914.', 1, 1, 2),
('The Hundred Years’ War lasted 100 years.', 0, 1, 2),
('The Crusades were religious wars.', 1, 1, 2),
('The Great Fire of London occurred in the 18th century.', 0, 1, 2),
('The printing press was invented by Johannes Gutenberg.', 1, 1, 2),
('The Ottoman Empire was based in Africa.', 0, 1, 2),
('The Boston Tea Party was a protest against taxes.', 1, 1, 2),
('The Berlin Airlift occurred during World War II.', 0, 1, 2),
('The Age of Exploration began in the 15th century.', 1, 1, 2),
('The Glorious Revolution was in France.', 0, 1, 2),
('The steam engine was invented in the 18th century.', 1, 1, 2);

-- History (cat_id=2), Medium (diff_id=2)
INSERT INTO TrueFalseQuestions (questionText, correctAnswer, diff_id, cat_id) VALUES
('The Treaty of Tordesillas was signed in 1494.', 1, 2, 2),
('The War of 1812 was fought between France and Russia.', 0, 2, 2),
('The Meiji Restoration occurred in Japan.', 1, 2, 2),
('The Battle of Trafalgar was in 1805.', 1, 2, 2),
('The Taiping Rebellion was in China.', 1, 2, 2),
('The Congress of Vienna occurred in the 17th century.', 0, 2, 2),
('The Sepoy Mutiny was in India.', 1, 2, 2),
('The Boxer Rebellion was in Japan.', 0, 2, 2),
('The Louisiana Purchase was made by the United States.', 1, 2, 2),
('The Battle of Austerlitz was fought by Napoleon.', 1, 2, 2),
('The Opium Wars were fought in Africa.', 0, 2, 2),
('The Emancipation Proclamation was issued in 1863.', 1, 2, 2),
('The Zulu War was fought in South Africa.', 1, 2, 2),
('The Treaty of Guadalupe Hidalgo ended the Mexican-American War.', 1, 2, 2),
('The Crimean War was fought in the 20th century.', 0, 2, 2),
('The Monroe Doctrine was issued by the United States.', 1, 2, 2),
('The Battle of Gettysburg was in the American Civil War.', 1, 2, 2),
('The Dreyfus Affair was in Germany.', 0, 2, 2),
('The Franco-Prussian War unified Germany.', 1, 2, 2),
('The Irish Potato Famine occurred in the 1840s.', 1, 2, 2),
('The Scramble for Africa occurred in the 19th century.', 1, 2, 2),
('The Boer War was fought in Australia.', 0, 2, 2),
('The Reform Act of 1832 was in Britain.', 1, 2, 2),
('The Russo-Japanese War was in the 20th century.', 1, 2, 2),
('The Chartist Movement was in France.', 0, 2, 2);

-- History (cat_id=2), Hard (diff_id=3)
INSERT INTO TrueFalseQuestions (questionText, correctAnswer, diff_id, cat_id) VALUES
('The Peace of Augsburg was signed in 1555.', 1, 3, 2),
('The An Lushan Rebellion was in India.', 0, 3, 2),
('The Edict of Milan was issued in 313 CE.', 1, 3, 2),
('The Schmalkaldic League was formed in Germany.', 1, 3, 2),
('The Diet of Worms was in 1521.', 1, 3, 2),
('The Treaty of Brest-Litovsk was signed in 1918.', 1, 3, 2),
('The Mau Mau Uprising was in Kenya.', 1, 3, 2),
('The Battle of Lepanto was fought in Asia.', 0, 3, 2),
('The Domesday Book was compiled in England.', 1, 3, 2),
('The Revolt of the Comuneros was in Spain.', 1, 3, 2),
('The Nika Riots occurred in Constantinople.', 1, 3, 2),
('The Treaty of Waitangi was signed in New Zealand.', 1, 3, 2),
('The Bantu Migration occurred in Europe.', 0, 3, 2),
('The Council of Nicaea was held in 325 CE.', 1, 3, 2),
('The Hussite Wars were in Bohemia.', 1, 3, 2),
('The Glorious Revolution occurred in 1688.', 1, 3, 2),
('The Revolt of 1857 was in China.', 0, 3, 2),
('The Defenestration of Prague sparked the Thirty Years’ War.', 1, 3, 2),
('The Ashanti Empire was in West Africa.', 1, 3, 2),
('The Treaty of Kanagawa opened Japan to trade.', 1, 3, 2),
('The Pazzi Conspiracy was in Florence.', 1, 3, 2),
('The Great Schism of 1054 divided Christianity.', 1, 3, 2),
('The Battle of Plassey was in India.', 1, 3, 2),
('The Songhai Empire was in South America.', 0, 3, 2),
('The Investiture Controversy was in the 11th century.', 1, 3, 2);

-- Biology (cat_id=3), Easy (diff_id=1)
INSERT INTO TrueFalseQuestions (questionText, correctAnswer, diff_id, cat_id) VALUES
('The spine protects the spinal cord.', 1, 1, 3),
('Plants use nitrogen for photosynthesis.', 0, 1, 3),
('The diaphragm helps with breathing.', 1, 1, 3),
('The human body has one lung.', 0, 1, 3),
('Chlorophyll is found in plant leaves.', 1, 1, 3),
('The brain is part of the digestive system.', 0, 1, 3),
('Sweat helps regulate body temperature.', 1, 1, 3),
('Fish have feathers.', 0, 1, 3),
('The tongue is used for tasting food.', 1, 1, 3),
('The skeleton is made of cartilage only.', 0, 1, 3),
('The iris controls the size of the pupil.', 1, 1, 3),
('Mammals are cold-blooded animals.', 0, 1, 3),
('The esophagus transports food to the stomach.', 1, 1, 3),
('Trees are animals.', 0, 1, 3),
('The bladder stores urine.', 1, 1, 3),
('The skin is an organ.', 1, 1, 3),
('Birds have teeth instead of beaks.', 0, 1, 3),
('The thyroid gland regulates metabolism.', 1, 1, 3),
('The small intestine is shorter than the large intestine.', 0, 1, 3),
('Fungi are a type of plant.', 0, 1, 3),
('The cornea is part of the eye.', 1, 1, 3),
('The human body has 12 ribs.', 0, 1, 3),
('Pollen is produced by flowers.', 1, 1, 3),
('The appendix is essential for survival.', 0, 1, 3),
('The biceps are muscles in the arm.', 1, 1, 3);

-- Biology (cat_id=3), Medium (diff_id=2)
INSERT INTO TrueFalseQuestions (questionText, correctAnswer, diff_id, cat_id) VALUES
('The adrenal glands produce adrenaline.', 1, 2, 3),
('The Golgi apparatus is found in plant cells only.', 0, 2, 3),
('Symbiosis is a relationship between two organisms.', 1, 2, 3),
('The cerebellum is responsible for vision.', 0, 2, 3),
('Antibodies are produced by the immune system.', 1, 2, 3),
('The phloem transports nutrients in plants.', 1, 2, 3),
('The pituitary gland is in the brain.', 1, 2, 3),
('All bacteria are harmful to humans.', 0, 2, 3),
('The retina detects light in the eye.', 1, 2, 3),
('The trachea is part of the digestive system.', 0, 2, 3),
('Lipids are a type of macromolecule.', 1, 2, 3),
('The hypothalamus regulates body temperature.', 1, 2, 3),
('Frogs are reptiles.', 0, 2, 3),
('The pancreas produces glucagon.', 1, 2, 3),
('The vacuole stores water in plant cells.', 1, 2, 3),
('The aorta is a vein.', 0, 2, 3),
('Enzymes speed up chemical reactions.', 1, 2, 3),
('The thymus is part of the lymphatic system.', 1, 2, 3),
('Coral reefs are living organisms.', 1, 2, 3),
('The larynx is used for hearing.', 0, 2, 3),
('Fermentation produces alcohol in yeast.', 1, 2, 3),
('The clavicle is a bone in the leg.', 0, 2, 3),
('Tropism is a plant’s response to stimuli.', 1, 2, 3),
('The epidermis is the innermost layer of skin.', 0, 2, 3),
('Capillaries connect arteries and veins.', 1, 2, 3);

-- Biology (cat_id=3), Hard (diff_id=3)
INSERT INTO TrueFalseQuestions (questionText, correctAnswer, diff_id, cat_id) VALUES
('Telomeres protect chromosome ends.', 1, 3, 3),
('The nucleolus is found in mitochondria.', 0, 3, 3),
('Cytokinesis divides the cytoplasm during cell division.', 1, 3, 3),
('The lac operon is found in human cells.', 0, 3, 3),
('Epigenetics studies heritable changes in gene expression.', 1, 3, 3),
('The endosymbiotic theory explains the origin of chloroplasts.', 1, 3, 3),
('Introns are coding regions of DNA.', 0, 3, 3),
('The sodium-potassium pump maintains cell membrane potential.', 1, 3, 3),
('Glycolysis occurs in the nucleus.', 0, 3, 3),
('Allosteric regulation alters enzyme activity.', 1, 3, 3),
('The blastula is a stage in embryonic development.', 1, 3, 3),
('Plasmids are found in eukaryotic cells.', 0, 3, 3),
('The Hardy-Weinberg equilibrium describes population genetics.', 1, 3, 3),
('The xylem transports sugars in plants.', 0, 3, 3),
('Apoptosis is programmed cell death.', 1, 3, 3),
('The citric acid cycle occurs in the cytoplasm.', 0, 3, 3),
('Histones package DNA in eukaryotic cells.', 1, 3, 3),
('The sinoatrial node is in the brain.', 0, 3, 3),
('Autophagy recycles cellular components.', 1, 3, 3),
('The mesophyll is a leaf tissue for photosynthesis.', 1, 3, 3),
('The proton motive force drives ATP synthesis.', 1, 3, 3),
('The myelin sheath is found in plant cells.', 0, 3, 3),
('Crispr-Cas9 is a gene-editing tool.', 1, 3, 3),
('The loop of Henle is in the liver.', 0, 3, 3),
('Photophosphorylation occurs in chloroplasts.', 1, 3, 3);

-- Movies (cat_id=4), Easy (diff_id=1)
INSERT INTO TrueFalseQuestions (questionText, correctAnswer, diff_id, cat_id) VALUES
('Aladdin is a Disney animated film.', 1, 1, 4),
('The Hulk is a DC superhero.', 0, 1, 4),
('Cinderella is a princess in a Disney movie.', 1, 1, 4),
('The Smurfs are characters in a horror film.', 0, 1, 4),
('The Jungle Book features a bear named Baloo.', 1, 1, 4),
('Wonder Woman is a Marvel character.', 0, 1, 4),
('Beauty and the Beast is a live-action film only.', 0, 1, 4),
('Pocahontas is a Disney character.', 1, 1, 4),
('The Minions are from Despicable Me.', 1, 1, 4),
('Kung Fu Panda is a live-action film.', 0, 1, 4),
('The Emperor’s New Groove is a Disney movie.', 1, 1, 4),
('Shazam is a Marvel superhero.', 0, 1, 4),
('Monsters, Inc. features a character named Sulley.', 1, 1, 4),
('The Lego Movie is an animated film.', 1, 1, 4),
('Ice Age is about dinosaurs only.', 0, 1, 4),
('Tarzan is a Disney animated film.', 1, 1, 4),
('Captain Marvel is a male superhero.', 0, 1, 4),
('The Nightmare Before Christmas was directed by Tim Burton.', 1, 1, 4),
('Cloudy with a Chance of Meatballs is a live-action film.', 0, 1, 4),
('Hercules is a character in a Disney movie.', 1, 1, 4),
('The Fantastic Four are DC characters.', 0, 1, 4),
('Wreck-It Ralph is an animated film.', 1, 1, 4),
('Ant-Man is a Marvel superhero.', 1, 1, 4),
('The Secret Life of Pets is about farm animals.', 0, 1, 4),
('Pinocchio is a Disney character.', 1, 1, 4);

-- Movies (cat_id=4), Medium (diff_id=2)
INSERT INTO TrueFalseQuestions (questionText, correctAnswer, diff_id, cat_id) VALUES
('Whiplash is a film about a drummer.', 1, 2, 4),
('The Revenant is a comedy film.', 0, 2, 4),
('12 Years a Slave won an Oscar for Best Picture.', 1, 2, 4),
('The Grand Budapest Hotel is a documentary.', 0, 2, 4),
('Drive is a film starring Ryan Gosling.', 1, 2, 4),
('Room is a science fiction film.', 0, 2, 4),
('The Wolf of Wall Street was directed by Martin Scorsese.', 1, 2, 4),
('Birdman is a film about a superhero.', 0, 2, 4),
('Ex Machina is a film about artificial intelligence.', 1, 2, 4),
('Spotlight is a musical.', 0, 2, 4),
('The King’s Speech is about King George VI.', 1, 2, 4),
('Her is a film about time travel.', 0, 2, 4),
('The Social Network is about the founding of Facebook.', 1, 2, 4),
('Argo is a film about a space mission.', 0, 2, 4),
('Dallas Buyers Club is based on a true story.', 1, 2, 4),
('Boyhood was filmed over 12 years.', 1, 2, 4),
('The Artist is a silent film.', 1, 2, 4),
('Gravity is a film set on Earth.', 0, 2, 4),
('Inside Llewyn Davis is a Coen Brothers film.', 1, 2, 4),
('Sicario is a romantic comedy.', 0, 2, 4),
('The Theory of Everything is about Stephen Hawking.', 1, 2, 4),
('The Imitation Game is about cooking.', 0, 2, 4),
('Selma is about the civil rights movement.', 1, 2, 4),
('Nightcrawler is a film about journalism.', 1, 2, 4),
('Captain Phillips is a fantasy film.', 0, 2, 4);

-- Movies (cat_id=4), Hard (diff_id=3)
INSERT INTO TrueFalseQuestions (questionText, correctAnswer, diff_id, cat_id) VALUES
('Yojimbo is a film by Akira Kurosawa.', 1, 3, 4),
('The Seventh Seal is a comedy film.', 0, 3, 4),
('La Dolce Vita was directed by Federico Fellini.', 1, 3, 4),
('Tokyo Story is a Hollywood film.', 0, 3, 4),
('Breathless is a French New Wave film.', 1, 3, 4),
('Wild Strawberries is a science fiction film.', 0, 3, 4),
('Aguirre, the Wrath of God was directed by Werner Herzog.', 1, 3, 4),
('The 400 Blows is a documentary.', 0, 3, 4),
('Rashomon is a film about a samurai.', 1, 3, 4),
('Blow-Up is a British film by Michelangelo Antonioni.', 1, 3, 4),
('8? is a film by Ingmar Bergman.', 0, 3, 4),
('Persona is a Swedish film.', 1, 3, 4),
('L’Avventura is a horror film.', 0, 3, 4),
('Pather Panchali was directed by Satyajit Ray.', 1, 3, 4),
('Hiroshima Mon Amour is a Japanese film.', 0, 3, 4),
('The Rules of the Game is a French film.', 1, 3, 4),
('Andrei Rublev is a comedy film.', 0, 3, 4),
('Bicycle Thieves is an Italian neorealist film.', 1, 3, 4),
('The Battle of Algiers is a documentary.', 0, 3, 4),
('Ikiru is a film by Akira Kurosawa.', 1, 3, 4),
('La Strada is a film by Federico Fellini.', 1, 3, 4),
('Umberto D. is a French film.', 0, 3, 4),
('Cleo from 5 to 7 is a French New Wave film.', 1, 3, 4),
('Ordet is a Danish film.', 1, 3, 4),
('Z is a political thriller by Costa-Gavras.', 1, 3, 4);